import SwiftUI

/// Lemonade Design System Space tokens.
/// Provides a consistent and scalable way to manage spacing across interfaces.
/// These values can be used for margins, paddings, and gaps to create balanced layouts.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-spacing-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-spacing-token-converter.main.kts
///  
///  @generated by scripts/swiftui-spacing-token-converter.main.kts
/// 

/// Spacing token enum
public enum LemonadeSpacing {
    case spacing0
    case spacing50
    case spacing100
    case spacing200
    case spacing300
    case spacing400
    case spacing500
    case spacing600
    case spacing800
    case spacing1000
    case spacing1200
    case spacing1400
    case spacing1600
    case spacing1800
    case spacing2000

    /// Returns the CGFloat value for this spacing token
    public var value: CGFloat {
        switch self {
        case .spacing0: return 0
        case .spacing50: return 2
        case .spacing100: return 4
        case .spacing200: return 8
        case .spacing300: return 12
        case .spacing400: return 16
        case .spacing500: return 20
        case .spacing600: return 24
        case .spacing800: return 32
        case .spacing1000: return 40
        case .spacing1200: return 48
        case .spacing1400: return 56
        case .spacing1600: return 64
        case .spacing1800: return 72
        case .spacing2000: return 80
        }
    }
}

/// Protocol for spacing values
public protocol LemonadeSpaceValues {
    var spacing0: CGFloat { get }
    var spacing50: CGFloat { get }
    var spacing100: CGFloat { get }
    var spacing200: CGFloat { get }
    var spacing300: CGFloat { get }
    var spacing400: CGFloat { get }
    var spacing500: CGFloat { get }
    var spacing600: CGFloat { get }
    var spacing800: CGFloat { get }
    var spacing1000: CGFloat { get }
    var spacing1200: CGFloat { get }
    var spacing1400: CGFloat { get }
    var spacing1600: CGFloat { get }
    var spacing1800: CGFloat { get }
    var spacing2000: CGFloat { get }
}

/// Default spacing values implementation
public struct LemonadeSpaceValuesImpl: LemonadeSpaceValues {
    public let spacing0: CGFloat = LemonadeSpacing.spacing0.value
    public let spacing50: CGFloat = LemonadeSpacing.spacing50.value
    public let spacing100: CGFloat = LemonadeSpacing.spacing100.value
    public let spacing200: CGFloat = LemonadeSpacing.spacing200.value
    public let spacing300: CGFloat = LemonadeSpacing.spacing300.value
    public let spacing400: CGFloat = LemonadeSpacing.spacing400.value
    public let spacing500: CGFloat = LemonadeSpacing.spacing500.value
    public let spacing600: CGFloat = LemonadeSpacing.spacing600.value
    public let spacing800: CGFloat = LemonadeSpacing.spacing800.value
    public let spacing1000: CGFloat = LemonadeSpacing.spacing1000.value
    public let spacing1200: CGFloat = LemonadeSpacing.spacing1200.value
    public let spacing1400: CGFloat = LemonadeSpacing.spacing1400.value
    public let spacing1600: CGFloat = LemonadeSpacing.spacing1600.value
    public let spacing1800: CGFloat = LemonadeSpacing.spacing1800.value
    public let spacing2000: CGFloat = LemonadeSpacing.spacing2000.value

    public init() {}
}
