import SwiftUI

/// Lemonade Design System Font Size tokens.
/// Provides a consistent way to manage font sizes across interfaces.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-typography-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-typography-token-converter.main.kts
///  
///  @generated by scripts/swiftui-typography-token-converter.main.kts
/// 

/// Font size token enum
public enum LemonadeFontSizes {
    case fontSize250
    case fontSize300
    case fontSize350
    case fontSize400
    case fontSize450
    case fontSize500
    case fontSize600
    case fontSize700
    case fontSize800
    case fontSize900
    case fontSize1000
    case fontSize1200
    case fontSize1400
    case fontSize1600
    case fontSize1800

    /// The base font family for the design system
    public static let fontFamily: String = "Figtree"

    /// Returns the CGFloat value for this font size token
    public var value: CGFloat {
        switch self {
        case .fontSize250: return 10
        case .fontSize300: return 12
        case .fontSize350: return 14
        case .fontSize400: return 16
        case .fontSize450: return 18
        case .fontSize500: return 20
        case .fontSize600: return 24
        case .fontSize700: return 28
        case .fontSize800: return 32
        case .fontSize900: return 36
        case .fontSize1000: return 40
        case .fontSize1200: return 48
        case .fontSize1400: return 56
        case .fontSize1600: return 64
        case .fontSize1800: return 72
        }
    }
}

/// Protocol for font size values
public protocol LemonadeFontSizeValues {
    var fontSize250: CGFloat { get }
    var fontSize300: CGFloat { get }
    var fontSize350: CGFloat { get }
    var fontSize400: CGFloat { get }
    var fontSize450: CGFloat { get }
    var fontSize500: CGFloat { get }
    var fontSize600: CGFloat { get }
    var fontSize700: CGFloat { get }
    var fontSize800: CGFloat { get }
    var fontSize900: CGFloat { get }
    var fontSize1000: CGFloat { get }
    var fontSize1200: CGFloat { get }
    var fontSize1400: CGFloat { get }
    var fontSize1600: CGFloat { get }
    var fontSize1800: CGFloat { get }
}

/// Default font size values implementation
public struct LemonadeFontSizeValuesImpl: LemonadeFontSizeValues {
    public let fontSize250: CGFloat = LemonadeFontSizes.fontSize250.value
    public let fontSize300: CGFloat = LemonadeFontSizes.fontSize300.value
    public let fontSize350: CGFloat = LemonadeFontSizes.fontSize350.value
    public let fontSize400: CGFloat = LemonadeFontSizes.fontSize400.value
    public let fontSize450: CGFloat = LemonadeFontSizes.fontSize450.value
    public let fontSize500: CGFloat = LemonadeFontSizes.fontSize500.value
    public let fontSize600: CGFloat = LemonadeFontSizes.fontSize600.value
    public let fontSize700: CGFloat = LemonadeFontSizes.fontSize700.value
    public let fontSize800: CGFloat = LemonadeFontSizes.fontSize800.value
    public let fontSize900: CGFloat = LemonadeFontSizes.fontSize900.value
    public let fontSize1000: CGFloat = LemonadeFontSizes.fontSize1000.value
    public let fontSize1200: CGFloat = LemonadeFontSizes.fontSize1200.value
    public let fontSize1400: CGFloat = LemonadeFontSizes.fontSize1400.value
    public let fontSize1600: CGFloat = LemonadeFontSizes.fontSize1600.value
    public let fontSize1800: CGFloat = LemonadeFontSizes.fontSize1800.value

    public init() {}
}
