import SwiftUI

/// Lemonade Design System Shadow tokens.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-shadow-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-shadow-token-converter.main.kts
///  
///  @generated by scripts/swiftui-shadow-token-converter.main.kts
/// 

/// Shadow data structure
public struct LemonadeShadowData: Sendable {
    public let blur: CGFloat
    public let spread: CGFloat
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let color: Color

    public init(blur: CGFloat, spread: CGFloat, offsetX: CGFloat, offsetY: CGFloat, color: Color) {
        self.blur = blur
        self.spread = spread
        self.offsetX = offsetX
        self.offsetY = offsetY
        self.color = color
    }
}

/// Shadow token enum
public enum LemonadeShadow: CaseIterable, Sendable {
    case xsmall
    case small
    case medium
    case large
    case xlarge
    case none

    public var displayName: String {
        switch self {
        case .xsmall: return "X-Small"
        case .small: return "Small"
        case .medium: return "Medium"
        case .large: return "Large"
        case .xlarge: return "X-Large"
        case .none: return "None"
        }
    }

    /// Returns the shadow data layers for this shadow token
    public var shadowLayers: [LemonadeShadowData] {
        switch self {
        case .xsmall:
            return [
                LemonadeShadowData(blur: 2.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
            ]
        case .small:
            return [
                LemonadeShadowData(blur: 3.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
                LemonadeShadowData(blur: 2.0, spread: -1.0, offsetX: 0.0, offsetY: 1.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
            ]
        case .medium:
            return [
                LemonadeShadowData(blur: 3.0, spread: -2.0, offsetX: 0.0, offsetY: 2.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
                LemonadeShadowData(blur: 6.0, spread: -2.0, offsetX: 0.0, offsetY: 4.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
            ]
        case .large:
            return [
                LemonadeShadowData(blur: 6.0, spread: -4.0, offsetX: 0.0, offsetY: 4.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
                LemonadeShadowData(blur: 15.0, spread: -3.0, offsetX: 0.0, offsetY: 10.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
            ]
        case .xlarge:
            return [
                LemonadeShadowData(blur: 10.0, spread: -6.0, offsetX: 0.0, offsetY: 8.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
                LemonadeShadowData(blur: 25.0, spread: -5.0, offsetX: 0.0, offsetY: 20.0, color: Color(red: 0.00, green: 0.00, blue: 0.00, opacity: 0.10)),
            ]
        case .none:
            return [LemonadeShadowData(blur: 0, spread: 0, offsetX: 0, offsetY: 0, color: .clear)]
        }
    }
}

/// View modifier for applying Lemonade shadows
public struct LemonadeShadowModifier: ViewModifier {
    let shadow: LemonadeShadow
    /// When non-nil, overrides the per-layer token color for all layers.
    let color: Color?

    public init(shadow: LemonadeShadow, color: Color? = nil) {
        self.shadow = shadow
        self.color = color
    }

    public func body(content: Content) -> some View {
        let composited = content.compositingGroup()
        return composited.background {
            GeometryReader { proxy in
                ForEach(Array(shadow.shadowLayers.enumerated()), id: \.offset) { _, layer in
                    let spreadW = max(0, proxy.size.width + layer.spread * 2)
                    let spreadH = max(0, proxy.size.height + layer.spread * 2)
                    let scaleX = proxy.size.width == 0 ? 1 : spreadW / proxy.size.width
                    let scaleY = proxy.size.height == 0 ? 1 : spreadH / proxy.size.height
                    Rectangle()
                        .fill(color ?? layer.color)
                        .frame(width: spreadW, height: spreadH)
                        .mask {
                            composited
                                .scaleEffect(x: scaleX, y: scaleY)
                        }
                        .offset(x: layer.offsetX - layer.spread, y: layer.offsetY - layer.spread)
                        .blur(radius: layer.blur / 2)
                        .overlay(alignment: .topLeading) {
                            composited
                                .frame(width: proxy.size.width, height: proxy.size.height)
                                .blendMode(.destinationOut)
                        }
                        .compositingGroup()
                }
            }
        }
    }
}

public extension View {
    /// Applies a Lemonade shadow to the view.
    /// - Parameters:
    ///   - shadow: The shadow token to apply.
    ///   - color: Optional color override applied to all shadow layers.
    ///            Defaults to `nil`, which uses each layer's token color.
    func lemonadeShadow(_ shadow: LemonadeShadow, color: Color? = nil) -> some View {
        modifier(LemonadeShadowModifier(shadow: shadow, color: color))
    }
}