import SwiftUI

/// Lemonade Design System Shadow tokens.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-shadow-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-shadow-token-converter.main.kts
///  
///  @generated by scripts/swiftui-shadow-token-converter.main.kts
/// 

/// Shadow data structure
public struct LemonadeShadowData {
    public let blur: CGFloat
    public let spread: CGFloat
    public let offsetX: CGFloat
    public let offsetY: CGFloat

    public init(blur: CGFloat, spread: CGFloat, offsetX: CGFloat, offsetY: CGFloat) {
        self.blur = blur
        self.spread = spread
        self.offsetX = offsetX
        self.offsetY = offsetY
    }
}

/// Shadow token enum
public enum LemonadeShadow {
    case large
    case medium
    case small
    case xsmall
    case none

    /// Returns the shadow data layers for this shadow token
    public var shadowLayers: [LemonadeShadowData] {
        switch self {
        case .large:
            return [
                LemonadeShadowData(blur: 1.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0),
                LemonadeShadowData(blur: 8.0, spread: -8.0, offsetX: 0.0, offsetY: 8.0),
                LemonadeShadowData(blur: 28.0, spread: -12.0, offsetX: 0.0, offsetY: 24.0),
                LemonadeShadowData(blur: 48.0, spread: -8.0, offsetX: 0.0, offsetY: 32.0),
            ]
        case .medium:
            return [
                LemonadeShadowData(blur: 1.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0),
                LemonadeShadowData(blur: 32.0, spread: -6.0, offsetX: 0.0, offsetY: 16.0),
            ]
        case .small:
            return [
                LemonadeShadowData(blur: 1.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0),
                LemonadeShadowData(blur: 6.0, spread: -3.0, offsetX: 0.0, offsetY: 4.0),
            ]
        case .xsmall:
            return [
                LemonadeShadowData(blur: 1.0, spread: 0.0, offsetX: 0.0, offsetY: 1.0),
                LemonadeShadowData(blur: 3.0, spread: -3.0, offsetX: 0.0, offsetY: 3.0),
            ]
        case .none:
            return [LemonadeShadowData(blur: 0, spread: 0, offsetX: 0, offsetY: 0)]
        }
    }
}

/// View modifier for applying Lemonade shadows
public struct LemonadeShadowModifier: ViewModifier {
    let shadow: LemonadeShadow
    let color: Color

    public init(shadow: LemonadeShadow, color: Color = Color(red: 21/255, green: 34/255, blue: 21/255).opacity(0.18)) {
        self.shadow = shadow
        self.color = color
    }

    public func body(content: Content) -> some View {
        shadow.shadowLayers.reduce(AnyView(content)) { view, shadowData in
            AnyView(
                view.shadow(
                    color: color,
                    radius: shadowData.blur / 2,
                    x: shadowData.offsetX,
                    y: shadowData.offsetY
                )
            )
        }
    }
}

public extension View {
    /// Applies a Lemonade shadow to the view
    func lemonadeShadow(_ shadow: LemonadeShadow, color: Color = Color(red: 21/255, green: 34/255, blue: 21/255).opacity(0.18)) -> some View {
        modifier(LemonadeShadowModifier(shadow: shadow, color: color))
    }
}
