import SwiftUI

/// Lemonade Design System Size tokens.
/// Provides a consistent and scalable way to manage sizes across interfaces.
/// These values can be used for component dimensions to create balanced layouts.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-size-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-size-token-converter.main.kts
///  
///  @generated by scripts/swiftui-size-token-converter.main.kts
/// 

/// Size token enum
public enum LemonadeSizes {
    case size0
    case size50
    case size100
    case size150
    case size200
    case size250
    case size300
    case size350
    case size400
    case size450
    case size500
    case size550
    case size600
    case size700
    case size750
    case size800
    case size900
    case size1000
    case size1100
    case size1200
    case size1400
    case size1600

    /// Returns the CGFloat value for this size token
    public var value: CGFloat {
        switch self {
        case .size0: return 0
        case .size50: return 2
        case .size100: return 4
        case .size150: return 6
        case .size200: return 8
        case .size250: return 10
        case .size300: return 12
        case .size350: return 14
        case .size400: return 16
        case .size450: return 18
        case .size500: return 20
        case .size550: return 22
        case .size600: return 24
        case .size700: return 28
        case .size750: return 30
        case .size800: return 32
        case .size900: return 36
        case .size1000: return 40
        case .size1100: return 44
        case .size1200: return 48
        case .size1400: return 56
        case .size1600: return 64
        }
    }
}

/// Protocol for size values
public protocol LemonadeSizeValues {
    var size0: CGFloat { get }
    var size50: CGFloat { get }
    var size100: CGFloat { get }
    var size150: CGFloat { get }
    var size200: CGFloat { get }
    var size250: CGFloat { get }
    var size300: CGFloat { get }
    var size350: CGFloat { get }
    var size400: CGFloat { get }
    var size450: CGFloat { get }
    var size500: CGFloat { get }
    var size550: CGFloat { get }
    var size600: CGFloat { get }
    var size700: CGFloat { get }
    var size750: CGFloat { get }
    var size800: CGFloat { get }
    var size900: CGFloat { get }
    var size1000: CGFloat { get }
    var size1100: CGFloat { get }
    var size1200: CGFloat { get }
    var size1400: CGFloat { get }
    var size1600: CGFloat { get }
}

/// Default size values implementation
public struct LemonadeSizeValuesImpl: LemonadeSizeValues {
    public let size0: CGFloat = LemonadeSizes.size0.value
    public let size50: CGFloat = LemonadeSizes.size50.value
    public let size100: CGFloat = LemonadeSizes.size100.value
    public let size150: CGFloat = LemonadeSizes.size150.value
    public let size200: CGFloat = LemonadeSizes.size200.value
    public let size250: CGFloat = LemonadeSizes.size250.value
    public let size300: CGFloat = LemonadeSizes.size300.value
    public let size350: CGFloat = LemonadeSizes.size350.value
    public let size400: CGFloat = LemonadeSizes.size400.value
    public let size450: CGFloat = LemonadeSizes.size450.value
    public let size500: CGFloat = LemonadeSizes.size500.value
    public let size550: CGFloat = LemonadeSizes.size550.value
    public let size600: CGFloat = LemonadeSizes.size600.value
    public let size700: CGFloat = LemonadeSizes.size700.value
    public let size750: CGFloat = LemonadeSizes.size750.value
    public let size800: CGFloat = LemonadeSizes.size800.value
    public let size900: CGFloat = LemonadeSizes.size900.value
    public let size1000: CGFloat = LemonadeSizes.size1000.value
    public let size1100: CGFloat = LemonadeSizes.size1100.value
    public let size1200: CGFloat = LemonadeSizes.size1200.value
    public let size1400: CGFloat = LemonadeSizes.size1400.value
    public let size1600: CGFloat = LemonadeSizes.size1600.value

    public init() {}
}
