import SwiftUI

/// Lemonade Design System Radius tokens.
/// Sets a small, clear set of predefined radius values for UI elements to ensure
/// consistent, scalable rounding across the product.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-radius-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-radius-token-converter.main.kts
///  
///  @generated by scripts/swiftui-radius-token-converter.main.kts
/// 

/// Radius token enum
public enum LemonadeRadius {
    case radius0
    case radius50
    case radius100
    case radius150
    case radius200
    case radius300
    case radius400
    case radius500
    case radius600
    case radius800
    case radiusFull

    /// Returns the CGFloat value for this radius token
    public var value: CGFloat {
        switch self {
        case .radius0: return 0
        case .radius50: return 2
        case .radius100: return 4
        case .radius150: return 6
        case .radius200: return 8
        case .radius300: return 12
        case .radius400: return 16
        case .radius500: return 20
        case .radius600: return 24
        case .radius800: return 32
        case .radiusFull: return 999
        }
    }

    /// Returns a RoundedRectangle shape with this radius
    public var shape: RoundedRectangle {
        RoundedRectangle(cornerRadius: value)
    }
}

/// Protocol for radius values
public protocol LemonadeRadiusValues {
    var radius0: CGFloat { get }
    var radius50: CGFloat { get }
    var radius100: CGFloat { get }
    var radius150: CGFloat { get }
    var radius200: CGFloat { get }
    var radius300: CGFloat { get }
    var radius400: CGFloat { get }
    var radius500: CGFloat { get }
    var radius600: CGFloat { get }
    var radius800: CGFloat { get }
    var radiusFull: CGFloat { get }
}

/// Protocol for shape values
public protocol LemonadeShapes {
    var radius0: RoundedRectangle { get }
    var radius50: RoundedRectangle { get }
    var radius100: RoundedRectangle { get }
    var radius150: RoundedRectangle { get }
    var radius200: RoundedRectangle { get }
    var radius300: RoundedRectangle { get }
    var radius400: RoundedRectangle { get }
    var radius500: RoundedRectangle { get }
    var radius600: RoundedRectangle { get }
    var radius800: RoundedRectangle { get }
    var radiusFull: RoundedRectangle { get }
}

/// Default radius values implementation
public struct LemonadeRadiusValuesImpl: LemonadeRadiusValues {
    public let radius0: CGFloat = LemonadeRadius.radius0.value
    public let radius50: CGFloat = LemonadeRadius.radius50.value
    public let radius100: CGFloat = LemonadeRadius.radius100.value
    public let radius150: CGFloat = LemonadeRadius.radius150.value
    public let radius200: CGFloat = LemonadeRadius.radius200.value
    public let radius300: CGFloat = LemonadeRadius.radius300.value
    public let radius400: CGFloat = LemonadeRadius.radius400.value
    public let radius500: CGFloat = LemonadeRadius.radius500.value
    public let radius600: CGFloat = LemonadeRadius.radius600.value
    public let radius800: CGFloat = LemonadeRadius.radius800.value
    public let radiusFull: CGFloat = LemonadeRadius.radiusFull.value

    public init() {}
}

/// Default shapes implementation
public struct LemonadeShapesImpl: LemonadeShapes {
    public var radius0: RoundedRectangle { LemonadeRadius.radius0.shape }
    public var radius50: RoundedRectangle { LemonadeRadius.radius50.shape }
    public var radius100: RoundedRectangle { LemonadeRadius.radius100.shape }
    public var radius150: RoundedRectangle { LemonadeRadius.radius150.shape }
    public var radius200: RoundedRectangle { LemonadeRadius.radius200.shape }
    public var radius300: RoundedRectangle { LemonadeRadius.radius300.shape }
    public var radius400: RoundedRectangle { LemonadeRadius.radius400.shape }
    public var radius500: RoundedRectangle { LemonadeRadius.radius500.shape }
    public var radius600: RoundedRectangle { LemonadeRadius.radius600.shape }
    public var radius800: RoundedRectangle { LemonadeRadius.radius800.shape }
    public var radiusFull: RoundedRectangle { LemonadeRadius.radiusFull.shape }

    public init() {}
}
