import SwiftUI

/// Light theme implementation of semantic colors
/// See LemonadeSemanticColors for details on the color structure.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-theme-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-theme-token-converter.main.kts
///  
///  @generated by scripts/swiftui-theme-token-converter.main.kts
/// 

internal struct InteractionColorsImpl: InteractionColors {
    var bgNeutralSubtleInteractive: Color { LemonadePrimitiveColors.Solid.Black.black200 }
    var bgPositiveSubtleInteractive: Color { LemonadePrimitiveColors.Alpha.GreenLime.alpha200 }
    var bgInfoSubtleInteractive: Color { LemonadePrimitiveColors.Alpha.Blue.alpha200 }
    var bgNeutralInteractive: Color { LemonadePrimitiveColors.Solid.Neutral.neutral700 }
    var bgBrandHighInteractive: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime900 }
    var bgDefaultInteractive: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha50 }
    var bgCautionInteractive: Color { LemonadePrimitiveColors.Solid.Orange.orange600 }
    var bgPositiveInteractive: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime600 }
    var bgSubtleInteractive: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha100 }
    var bgInfoInteractive: Color { LemonadePrimitiveColors.Solid.Blue.blue600 }
    var bgCautionSubtleInteractive: Color { LemonadePrimitiveColors.Alpha.Orange.alpha200 }
    var bgCriticalInteractive: Color { LemonadePrimitiveColors.Solid.Red.red600 }
    var bgBrandInteractive: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime600 }
    var bgElevatedInteractive: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha200 }
    var bgCriticalSubtleInteractive: Color { LemonadePrimitiveColors.Alpha.Red.alpha200 }
    var bgDefaultPressed: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha100 }
    var bgElevatedPressed: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha300 }
    var bgBrandPressed: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime700 }
    var bgBrandHighPressed: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime950 }
    var bgCriticalPressed: Color { LemonadePrimitiveColors.Solid.Red.red700 }
    var bgCautionPressed: Color { LemonadePrimitiveColors.Solid.Amber.amber700 }
    var bgInfoPressed: Color { LemonadePrimitiveColors.Solid.Blue.blue700 }
    var bgPositivePressed: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime700 }
    var bgNeutralPressed: Color { LemonadePrimitiveColors.Solid.Neutral.neutral800 }
    var bgCautionSubtlePressed: Color { LemonadePrimitiveColors.Alpha.Amber.alpha300 }
    var bgInfoSubtlePressed: Color { LemonadePrimitiveColors.Alpha.Blue.alpha300 }
    var bgPositiveSubtlePressed: Color { LemonadePrimitiveColors.Alpha.GreenLime.alpha300 }
    var bgNeutralSubtlePressed: Color { LemonadePrimitiveColors.Solid.Black.black300 }
    var bgElevatedHighInteractive: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha300 }
    var bgBrandElevatedInteractive: Color { LemonadePrimitiveColors.Solid.White.white500 }
    var bgBrandElevatedPressed: Color { LemonadePrimitiveColors.Solid.White.white600 }
}

internal struct BorderColorsImpl: BorderColors {
    var borderBrandInverse: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime500 }
    var borderSelectedInverse: Color { LemonadePrimitiveColors.Solid.White.white700 }
    var borderNeutralMediumInverse: Color { LemonadePrimitiveColors.Solid.White.white300 }
    var borderNeutralLowInverse: Color { LemonadePrimitiveColors.Solid.White.white100 }
    var borderAlwaysDark: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha900 }
    var borderPositiveSubtle: Color { LemonadePrimitiveColors.Alpha.GreenLime.alpha500 }
    var borderInfoSubtle: Color { LemonadePrimitiveColors.Alpha.Blue.alpha500 }
    var borderCautionSubtle: Color { LemonadePrimitiveColors.Alpha.Orange.alpha500 }
    var borderCriticalSubtle: Color { LemonadePrimitiveColors.Alpha.Red.alpha500 }
    var borderPositive: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime700 }
    var borderInfo: Color { LemonadePrimitiveColors.Solid.Blue.blue700 }
    var borderCaution: Color { LemonadePrimitiveColors.Solid.Amber.amber700 }
    var borderOnBrandMedium: Color { LemonadePrimitiveColors.Solid.White.white500 }
    var borderBrand: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime700 }
    var borderSelected: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha900 }
    var borderOnBrandLow: Color { LemonadePrimitiveColors.Solid.White.white300 }
    var borderOnBrandHigh: Color { LemonadePrimitiveColors.Solid.White.white700 }
    var borderCritical: Color { LemonadePrimitiveColors.Solid.Red.red700 }
    var borderNeutralLow: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha100 }
    var borderNeutralMedium: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha200 }
    var borderAlwaysLight: Color { LemonadePrimitiveColors.Solid.White.white950 }
    var borderNeutralHigh: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha300 }
    var borderNeutralHighInverse: Color { LemonadePrimitiveColors.Solid.White.white400 }
}

internal struct ContentColorsImpl: ContentColors {
    var contentOnBrandLow: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime700 }
    var contentBrand: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime700 }
    var contentCaution: Color { LemonadePrimitiveColors.Solid.Amber.amber700 }
    var contentInfo: Color { LemonadePrimitiveColors.Solid.Blue.blue800 }
    var contentTertiary: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha400 }
    var contentAlwaysLight: Color { LemonadePrimitiveColors.Solid.White.white950 }
    var contentSecondary: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha600 }
    var contentPrimaryInverse: Color { LemonadePrimitiveColors.Solid.White.white950 }
    var contentPositive: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime700 }
    var contentTertiaryInverse: Color { LemonadePrimitiveColors.Solid.White.white700 }
    var contentAlwaysDark: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha950 }
    var contentNeutral: Color { LemonadePrimitiveColors.Solid.Neutral.neutral950 }
    var contentBrandInverse: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime500 }
    var contentSecondaryInverse: Color { LemonadePrimitiveColors.Solid.White.white900 }
    var contentCritical: Color { LemonadePrimitiveColors.Solid.Red.red600 }
    var contentOnBrandHigh: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime900 }
    var contentPrimary: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha900 }
    var contentCautionOnColor: Color { LemonadePrimitiveColors.Solid.Amber.amber400 }
    var contentInfoOnColor: Color { LemonadePrimitiveColors.Solid.Blue.blue400 }
    var contentPositiveOnColor: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime400 }
    var contentNeutralOnColor: Color { LemonadePrimitiveColors.Solid.White.white700 }
    var contentBrandHigh: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime800 }
}

internal struct BackgroundColorsImpl: BackgroundColors {
    var bgAlwaysLight: Color { LemonadePrimitiveColors.Solid.White.white950 }
    var bgAlwaysDark: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha950 }
    var bgDefaultInverse: Color { LemonadePrimitiveColors.Solid.Neutral.neutral950 }
    var bgNeutralSubtle: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha100 }
    var bgCautionSubtle: Color { LemonadePrimitiveColors.Alpha.Amber.alpha100 }
    var bgCriticalSubtle: Color { LemonadePrimitiveColors.Alpha.Red.alpha100 }
    var bgNeutral: Color { LemonadePrimitiveColors.Solid.Neutral.neutral600 }
    var bgBrandSubtle: Color { LemonadePrimitiveColors.Alpha.YellowLime.alpha200 }
    var bgSubtleInverse: Color { LemonadePrimitiveColors.Solid.Neutral.neutral900 }
    var bgBrandElevated: Color { LemonadePrimitiveColors.Solid.White.white400 }
    var bgPositiveSubtle: Color { LemonadePrimitiveColors.Alpha.GreenLime.alpha100 }
    var bgDefault: Color { LemonadePrimitiveColors.Solid.White.white950 }
    var bgCritical: Color { LemonadePrimitiveColors.Solid.Red.red500 }
    var bgBrandHigh: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime800 }
    var bgCaution: Color { LemonadePrimitiveColors.Solid.Amber.amber600 }
    var bgBrand: Color { LemonadePrimitiveColors.Solid.YellowLime.yellowLime500 }
    var bgElevated: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha100 }
    var bgElevatedInverse: Color { LemonadePrimitiveColors.Solid.White.white50 }
    var bgSubtle: Color { LemonadePrimitiveColors.Solid.Neutral.neutral50 }
    var bgInfo: Color { LemonadePrimitiveColors.Solid.Blue.blue600 }
    var bgPositive: Color { LemonadePrimitiveColors.Solid.GreenLime.greenLime600 }
    var bgInfoSubtle: Color { LemonadePrimitiveColors.Alpha.Blue.alpha100 }
    var bgElevatedHigh: Color { LemonadePrimitiveColors.Alpha.Neutral.alpha200 }
}

/// Light theme implementation
public struct LemonadeLightTheme: LemonadeSemanticColors {
    public let interaction: InteractionColors = InteractionColorsImpl()
    public let border: BorderColors = BorderColorsImpl()
    public let content: ContentColors = ContentColorsImpl()
    public let background: BackgroundColors = BackgroundColorsImpl()

    public init() {}
}
