import SwiftUI
import UIKit

/// Lemonade Design System Icons.
/// Icons are loaded from the asset catalog bundled with this module.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-svg-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-svg-converter.main.kts
///  
///  @generated by scripts/swiftui-svg-converter.main.kts
/// 

/// Icon token enum
public enum LemonadeIcon: String, CaseIterable {
    case teyaSymbol = "Teya Symbol"
    case airplane = "airplane"
    case arrowCornerDownLeft = "arrow-corner-down-left"
    case arrowCornerDownLeftSlash = "arrow-corner-down-left-slash"
    case arrowCornerDownRight = "arrow-corner-down-right"
    case arrowCornerLeftDown = "arrow-corner-left-down"
    case arrowCornerLeftUp = "arrow-corner-left-up"
    case arrowCornerRightDown = "arrow-corner-right-down"
    case arrowCornerRightUp = "arrow-corner-right-up"
    case arrowCornerTopLeft = "arrow-corner-top-left"
    case arrowCornerTopRight = "arrow-corner-top-right"
    case arrowDown = "arrow-down"
    case arrowDownLeft = "arrow-down-left"
    case arrowDownRight = "arrow-down-right"
    case arrowLeft = "arrow-left"
    case arrowLeftRight = "arrow-left-right"
    case arrowRight = "arrow-right"
    case arrowRotateCcw = "arrow-rotate-ccw"
    case arrowRotateCcwMoney = "arrow-rotate-ccw-money"
    case arrowRotateCw = "arrow-rotate-cw"
    case arrowRotateRightLeft = "arrow-rotate-right-left"
    case arrowSplit = "arrow-split"
    case arrowUp = "arrow-up"
    case arrowUpLeft = "arrow-up-left"
    case arrowUpRight = "arrow-up-right"
    case arrowUpToLine = "arrow-up-to-line"
    case arrowsExchange = "arrows-exchange"
    case atSign = "at-sign"
    case bank = "bank"
    case bankSolid = "bank-solid"
    case basket = "basket"
    case basketPlus = "basket-plus"
    case basketRemove = "basket-remove"
    case batteryHalf = "battery-half"
    case bell = "bell"
    case brandTeyaSquare = "brand-teya-square"
    case brandTeyaSymbol = "brand-teya-symbol"
    case briefcase = "briefcase"
    case bubbles = "bubbles"
    case bug = "bug"
    case buildings = "buildings"
    case calculator = "calculator"
    case calendar = "calendar"
    case calendarArrowUp = "calendar-arrow-up"
    case calendarCheck = "calendar-check"
    case calendarCheckSolid = "calendar-check-solid"
    case calendarClock = "calendar-clock"
    case calendarDay = "calendar-day"
    case calendarSearch = "calendar-search"
    case camera = "camera"
    case car = "car"
    case card = "card"
    case cardCog = "card-cog"
    case cardMachine = "card-machine"
    case cardRestricted = "card-restricted"
    case cards = "cards"
    case chart = "chart"
    case chartSolid = "chart-solid"
    case chartTrending = "chart-trending"
    case check = "check"
    case checkDouble = "check-double"
    case checkPartial = "check-partial"
    case checkSmall = "check-small"
    case chevronDown = "chevron-down"
    case chevronDownSmall = "chevron-down-small"
    case chevronLeft = "chevron-left"
    case chevronLeftSmall = "chevron-left-small"
    case chevronRight = "chevron-right"
    case chevronRightSmall = "chevron-right-small"
    case chevronTop = "chevron-top"
    case chevronTopSmall = "chevron-top-small"
    case chevronUpDown = "chevron-up-down"
    case circleAlert = "circle-alert"
    case circleCheck = "circle-check"
    case circleCheckSolid = "circle-check-solid"
    case circleEllipsis = "circle-ellipsis"
    case circleHelp = "circle-help"
    case circleInfo = "circle-info"
    case circleX = "circle-x"
    case circleXSolid = "circle-x-solid"
    case clock = "clock"
    case clockArrowDown = "clock-arrow-down"
    case clockArrowUp = "clock-arrow-up"
    case clockCross = "clock-cross"
    case coins = "coins"
    case coinsStack = "coins-stack"
    case compass = "compass"
    case cookie = "cookie"
    case copy = "copy"
    case cornerUpLeft = "corner-up-left"
    case download = "download"
    case ellipsisHorizontal = "ellipsis-horizontal"
    case ellipsisVertical = "ellipsis-vertical"
    case emojiAnnoyed = "emoji-annoyed"
    case emojiSad = "emoji-sad"
    case emojiSmile = "emoji-smile"
    case envelope = "envelope"
    case equal = "equal"
    case equalApproximately = "equal-approximately"
    case externalLink = "external-link"
    case eyeClosed = "eye-closed"
    case eyeOpen = "eye-open"
    case file = "file"
    case fileChart = "file-chart"
    case fileCheck = "file-check"
    case fileGear = "file-gear"
    case fileMoney = "file-money"
    case fileSpreadsheet = "file-spreadsheet"
    case fileText = "file-text"
    case fingerPrint = "finger-print"
    case floppyDisk = "floppy-disk"
    case gauge = "gauge"
    case gear = "gear"
    case gearSolid = "gear-solid"
    case gift = "gift"
    case globe = "globe"
    case grid = "grid"
    case group = "group"
    case hammer = "hammer"
    case handCoins = "hand-coins"
    case handshake = "handshake"
    case heart = "heart"
    case heartSolid = "heart-solid"
    case home = "home"
    case homeSolid = "home-solid"
    case hourglass = "hourglass"
    case image = "image"
    case inbox = "inbox"
    case incognito = "incognito"
    case key = "key"
    case laptop = "laptop"
    case lightbulb = "lightbulb"
    case lightning = "lightning"
    case limit = "limit"
    case link = "link"
    case list = "list"
    case loader = "loader"
    case logIn = "log-in"
    case logOut = "log-out"
    case mapPin = "map-pin"
    case maximize = "maximize"
    case maximizeMini = "maximize-mini"
    case megaphone = "megaphone"
    case menu = "menu"
    case microphone = "microphone"
    case microphoneSlash = "microphone-slash"
    case minus = "minus"
    case money = "money"
    case moneyArrowDown = "money-arrow-down"
    case moneyArrowUp = "money-arrow-up"
    case moneyDollar = "money-dollar"
    case moneyDollarPlus = "money-dollar-plus"
    case moneyEuro = "money-euro"
    case moneyHandSolid = "money-hand-solid"
    case moneyPounds = "money-pounds"
    case nfc = "nfc"
    case numpad = "numpad"
    case package = "package"
    case padlock = "padlock"
    case padlockOpen = "padlock-open"
    case paperclip = "paperclip"
    case passport = "passport"
    case penSignature = "pen-signature"
    case pencilLine = "pencil-line"
    case percentage = "percentage"
    case phone = "phone"
    case plus = "plus"
    case plusSmall = "plus-small"
    case pound = "pound"
    case printer = "printer"
    case qrCode = "qr-code"
    case receipt = "receipt"
    case receiptTax = "receipt-tax"
    case rescueRing = "rescue-ring"
    case rotateMoney = "rotate-money"
    case scanFace = "scan-face"
    case search = "search"
    case send = "send"
    case settingsSlider = "settings-slider"
    case share = "share"
    case shield = "shield"
    case shieldKeyhole = "shield-keyhole"
    case shoppingBag = "shopping-bag"
    case smartphone = "smartphone"
    case snowflake = "snowflake"
    case sparkles = "sparkles"
    case squarePencil = "square-pencil"
    case squarePlus = "square-plus"
    case squarePlusSolid = "square-plus-solid"
    case stackThree = "stack-three"
    case star = "star"
    case starSolid = "star-solid"
    case stocks = "stocks"
    case store = "store"
    case stores = "stores"
    case supportChat = "support-chat"
    case thumbDown = "thumb-down"
    case thumbUp = "thumb-up"
    case times = "times"
    case translate = "translate"
    case trash = "trash"
    case triangleAlert = "triangle-alert"
    case trophy = "trophy"
    case truck = "truck"
    case undo = "undo"
    case user = "user"
    case userCoins = "user-coins"
    case userGear = "user-gear"
    case userKey = "user-key"
    case userPlus = "user-plus"
    case userRemove = "user-remove"
    case userSuccess = "user-success"
    case users = "users"
    case wifi = "wifi"

    /// Returns the Image for this icon from the Lemonade bundle's asset catalog
    public var image: Image {
        if let uiImage = UIImage(named: rawValue, in: .lemonade, compatibleWith: nil) {
            return Image(uiImage: uiImage).renderingMode(.template)
        }
        return Image(systemName: "questionmark.square")
    }
}

/// Icon size enum
public enum LemonadeIconSize {
    case small
    case medium
    case large

    public var value: CGFloat {
        switch self {
        case .small: return 16
        case .medium: return 24
        case .large: return 32
        }
    }
}

public extension View {
    /// Applies Lemonade icon styling
    func lemonadeIcon(size: LemonadeIconSize = .medium, color: Color? = nil) -> some View {
        self
            .frame(width: size.value, height: size.value)
            .foregroundColor(color)
    }
}
