import SwiftUI

/// Lemonade Design System Opacity tokens.
/// Provides a consistent and scalable way to manage opacity across interfaces.
/// These values can be used for disabled components and general transparency handling.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-opacity-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-opacity-token-converter.main.kts
///  
///  @generated by scripts/swiftui-opacity-token-converter.main.kts
/// 

/// Base opacity values
public protocol BaseOpacity {
    var opacity0: Double { get }
    var opacity5: Double { get }
    var opacity10: Double { get }
    var opacity20: Double { get }
    var opacity30: Double { get }
    var opacity40: Double { get }
    var opacity50: Double { get }
    var opacity60: Double { get }
    var opacity70: Double { get }
    var opacity80: Double { get }
    var opacity90: Double { get }
    var opacity100: Double { get }
}

/// State opacity values
public protocol StateOpacity {
    var opacityPressed: Double { get }
    var opacityDisabled: Double { get }
}

/// Protocol defining opacity categories
public protocol LemonadeOpacity {
    var base: BaseOpacity { get }
    var state: StateOpacity { get }
}

internal struct BaseOpacityImpl: BaseOpacity {
    let opacity0: Double = 0.0
    let opacity5: Double = 0.05
    let opacity10: Double = 0.1
    let opacity20: Double = 0.2
    let opacity30: Double = 0.3
    let opacity40: Double = 0.4
    let opacity50: Double = 0.5
    let opacity60: Double = 0.6
    let opacity70: Double = 0.7
    let opacity80: Double = 0.8
    let opacity90: Double = 0.9
    let opacity100: Double = 1.0
}

internal struct StateOpacityImpl: StateOpacity {
    let opacityPressed: Double = 0.2
    let opacityDisabled: Double = 0.4
}

/// Default opacity implementation
public struct LemonadeOpacityTokens: LemonadeOpacity {
    public let base: BaseOpacity = BaseOpacityImpl()
    public let state: StateOpacity = StateOpacityImpl()

    public init() {}
}
