import SwiftUI

/// Adaptive theme that uses Asset Catalog colors with built-in light/dark appearance variants.
///
/// Returns `Color` values from the asset catalog that automatically adapt to the
/// system's current appearance (light/dark mode) without any manual switching.
///
/// Usage:
/// ```swift
/// // Set once at app startup — no need to ever switch
/// LemonadeTheme.colors = LemonadeAdaptiveTheme()
/// ```
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-theme-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-theme-token-converter.main.kts
///  
///  @generated by scripts/swiftui-theme-token-converter.main.kts
/// 

private struct AdaptiveInteractionColors: InteractionColors {
    var bgNeutralSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-neutral-subtle-interactive", bundle: .lemonade) }
    var bgPositiveSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-positive-subtle-interactive", bundle: .lemonade) }
    var bgInfoSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-info-subtle-interactive", bundle: .lemonade) }
    var bgNeutralInteractive: Color { Color("lemonade-interaction-interactive-background-bg-neutral-interactive", bundle: .lemonade) }
    var bgBrandHighInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-high-interactive", bundle: .lemonade) }
    var bgDefaultInteractive: Color { Color("lemonade-interaction-interactive-background-bg-default-interactive", bundle: .lemonade) }
    var bgCautionInteractive: Color { Color("lemonade-interaction-interactive-background-bg-caution-interactive", bundle: .lemonade) }
    var bgPositiveInteractive: Color { Color("lemonade-interaction-interactive-background-bg-positive-interactive", bundle: .lemonade) }
    var bgSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-subtle-interactive", bundle: .lemonade) }
    var bgInfoInteractive: Color { Color("lemonade-interaction-interactive-background-bg-info-interactive", bundle: .lemonade) }
    var bgCautionSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-caution-subtle-interactive", bundle: .lemonade) }
    var bgCriticalInteractive: Color { Color("lemonade-interaction-interactive-background-bg-critical-interactive", bundle: .lemonade) }
    var bgBrandInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-interactive", bundle: .lemonade) }
    var bgElevatedInteractive: Color { Color("lemonade-interaction-interactive-background-bg-elevated-interactive", bundle: .lemonade) }
    var bgCriticalSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-critical-subtle-interactive", bundle: .lemonade) }
    var bgDefaultPressed: Color { Color("lemonade-interaction-pressed-background-bg-default-pressed", bundle: .lemonade) }
    var bgSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-subtle-pressed", bundle: .lemonade) }
    var bgElevatedPressed: Color { Color("lemonade-interaction-pressed-background-bg-elevated-pressed", bundle: .lemonade) }
    var bgBrandPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-pressed", bundle: .lemonade) }
    var bgBrandHighPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-high-pressed", bundle: .lemonade) }
    var bgCriticalPressed: Color { Color("lemonade-interaction-pressed-background-bg-critical-pressed", bundle: .lemonade) }
    var bgCautionPressed: Color { Color("lemonade-interaction-pressed-background-bg-caution-pressed", bundle: .lemonade) }
    var bgInfoPressed: Color { Color("lemonade-interaction-pressed-background-bg-info-pressed", bundle: .lemonade) }
    var bgPositivePressed: Color { Color("lemonade-interaction-pressed-background-bg-positive-pressed", bundle: .lemonade) }
    var bgNeutralPressed: Color { Color("lemonade-interaction-pressed-background-bg-neutral-pressed", bundle: .lemonade) }
    var bgCriticalSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-critical-subtle-pressed", bundle: .lemonade) }
    var bgCautionSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-caution-subtle-pressed", bundle: .lemonade) }
    var bgInfoSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-info-subtle-pressed", bundle: .lemonade) }
    var bgPositiveSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-positive-subtle-pressed", bundle: .lemonade) }
    var bgNeutralSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-neutral-subtle-pressed", bundle: .lemonade) }
    var bgElevatedHighInteractive: Color { Color("lemonade-interaction-interactive-background-bg-elevated-high-interactive", bundle: .lemonade) }
    var bgBrandElevatedInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-elevated-interactive", bundle: .lemonade) }
    var bgBrandElevatedPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-elevated-pressed", bundle: .lemonade) }
}

private struct AdaptiveBorderColors: BorderColors {
    var borderBrandInverse: Color { Color("lemonade-border-inverse-border-brand-inverse", bundle: .lemonade) }
    var borderSelectedInverse: Color { Color("lemonade-border-inverse-border-selected-inverse", bundle: .lemonade) }
    var borderNeutralMediumInverse: Color { Color("lemonade-border-inverse-border-neutral-medium-inverse", bundle: .lemonade) }
    var borderNeutralLowInverse: Color { Color("lemonade-border-inverse-border-neutral-low-inverse", bundle: .lemonade) }
    var borderAlwaysDark: Color { Color("lemonade-border-fixed-border-always-dark", bundle: .lemonade) }
    var borderPositiveSubtle: Color { Color("lemonade-border-voice-border-positive-subtle", bundle: .lemonade) }
    var borderInfoSubtle: Color { Color("lemonade-border-voice-border-info-subtle", bundle: .lemonade) }
    var borderCautionSubtle: Color { Color("lemonade-border-voice-border-caution-subtle", bundle: .lemonade) }
    var borderCriticalSubtle: Color { Color("lemonade-border-voice-border-critical-subtle", bundle: .lemonade) }
    var borderPositive: Color { Color("lemonade-border-voice-border-positive", bundle: .lemonade) }
    var borderInfo: Color { Color("lemonade-border-voice-border-info", bundle: .lemonade) }
    var borderCaution: Color { Color("lemonade-border-voice-border-caution", bundle: .lemonade) }
    var borderOnBrandMedium: Color { Color("lemonade-border-brand-border-on-brand-medium", bundle: .lemonade) }
    var borderBrand: Color { Color("lemonade-border-brand-border-brand", bundle: .lemonade) }
    var borderSelected: Color { Color("lemonade-border-border-selected", bundle: .lemonade) }
    var borderOnBrandLow: Color { Color("lemonade-border-brand-border-on-brand-low", bundle: .lemonade) }
    var borderOnBrandHigh: Color { Color("lemonade-border-brand-border-on-brand-high", bundle: .lemonade) }
    var borderCritical: Color { Color("lemonade-border-voice-border-critical", bundle: .lemonade) }
    var borderNeutralLow: Color { Color("lemonade-border-border-neutral-low", bundle: .lemonade) }
    var borderNeutralMedium: Color { Color("lemonade-border-border-neutral-medium", bundle: .lemonade) }
    var borderAlwaysLight: Color { Color("lemonade-border-fixed-border-always-light", bundle: .lemonade) }
    var borderNeutralHigh: Color { Color("lemonade-border-border-neutral-high", bundle: .lemonade) }
    var borderNeutralHighInverse: Color { Color("lemonade-border-inverse-border-neutral-high-inverse", bundle: .lemonade) }
    var borderAlwaysLightLow: Color { Color("lemonade-border-fixed-border-always-light-low", bundle: .lemonade) }
    var borderAlwaysLightMedium: Color { Color("lemonade-border-fixed-border-always-light-medium", bundle: .lemonade) }
    var borderAlwaysLightHigh: Color { Color("lemonade-border-fixed-border-always-light-high", bundle: .lemonade) }
    var borderAlwaysDarkLow: Color { Color("lemonade-border-fixed-border-always-dark-low", bundle: .lemonade) }
    var borderAlwaysDarkMedium: Color { Color("lemonade-border-fixed-border-always-dark-medium", bundle: .lemonade) }
    var borderAlwaysDarkHigh: Color { Color("lemonade-border-fixed-border-always-dark-high", bundle: .lemonade) }
}

private struct AdaptiveContentColors: ContentColors {
    var contentOnBrandLow: Color { Color("lemonade-content-brand-content-on-brand-low", bundle: .lemonade) }
    var contentBrand: Color { Color("lemonade-content-brand-content-brand", bundle: .lemonade) }
    var contentCaution: Color { Color("lemonade-content-voice-content-caution", bundle: .lemonade) }
    var contentInfo: Color { Color("lemonade-content-voice-content-info", bundle: .lemonade) }
    var contentTertiary: Color { Color("lemonade-content-content-tertiary", bundle: .lemonade) }
    var contentAlwaysLight: Color { Color("lemonade-content-fixed-content-always-light", bundle: .lemonade) }
    var contentSecondary: Color { Color("lemonade-content-content-secondary", bundle: .lemonade) }
    var contentPrimaryInverse: Color { Color("lemonade-content-inverse-content-primary-inverse", bundle: .lemonade) }
    var contentPositive: Color { Color("lemonade-content-voice-content-positive", bundle: .lemonade) }
    var contentTertiaryInverse: Color { Color("lemonade-content-inverse-content-tertiary-inverse", bundle: .lemonade) }
    var contentAlwaysDark: Color { Color("lemonade-content-fixed-content-always-dark", bundle: .lemonade) }
    var contentNeutral: Color { Color("lemonade-content-voice-content-neutral", bundle: .lemonade) }
    var contentBrandInverse: Color { Color("lemonade-content-inverse-content-brand-inverse", bundle: .lemonade) }
    var contentSecondaryInverse: Color { Color("lemonade-content-inverse-content-secondary-inverse", bundle: .lemonade) }
    var contentCritical: Color { Color("lemonade-content-voice-content-critical", bundle: .lemonade) }
    var contentOnBrandHigh: Color { Color("lemonade-content-brand-content-on-brand-high", bundle: .lemonade) }
    var contentPrimary: Color { Color("lemonade-content-content-primary", bundle: .lemonade) }
    var contentCriticalOnColor: Color { Color("lemonade-content-voice-on color-content-critical-on-color", bundle: .lemonade) }
    var contentCautionOnColor: Color { Color("lemonade-content-voice-on color-content-caution-on-color", bundle: .lemonade) }
    var contentInfoOnColor: Color { Color("lemonade-content-voice-on color-content-info-on-color", bundle: .lemonade) }
    var contentPositiveOnColor: Color { Color("lemonade-content-voice-on color-content-positive-on-color", bundle: .lemonade) }
    var contentNeutralOnColor: Color { Color("lemonade-content-voice-on color-content-neutral-on-color", bundle: .lemonade) }
    var contentBrandHigh: Color { Color("lemonade-content-brand-content-brand-high", bundle: .lemonade) }
}

private struct AdaptiveBackgroundColors: BackgroundColors {
    var bgTransparent: Color { Color("lemonade-background-fixed-bg-transparent", bundle: .lemonade) }
    var bgAlwaysLight: Color { Color("lemonade-background-fixed-bg-always-light", bundle: .lemonade) }
    var bgAlwaysDark: Color { Color("lemonade-background-fixed-bg-always-dark", bundle: .lemonade) }
    var bgDefaultInverse: Color { Color("lemonade-background-inverse-bg-default-inverse", bundle: .lemonade) }
    var bgNeutralSubtle: Color { Color("lemonade-background-voice-bg-neutral-subtle", bundle: .lemonade) }
    var bgCautionSubtle: Color { Color("lemonade-background-voice-bg-caution-subtle", bundle: .lemonade) }
    var bgCriticalSubtle: Color { Color("lemonade-background-voice-bg-critical-subtle", bundle: .lemonade) }
    var bgNeutral: Color { Color("lemonade-background-voice-bg-neutral", bundle: .lemonade) }
    var bgBrandSubtle: Color { Color("lemonade-background-brand-bg-brand-subtle", bundle: .lemonade) }
    var bgSubtleInverse: Color { Color("lemonade-background-inverse-bg-subtle-inverse", bundle: .lemonade) }
    var bgBrandElevated: Color { Color("lemonade-background-brand-bg-brand-elevated", bundle: .lemonade) }
    var bgPositiveSubtle: Color { Color("lemonade-background-voice-bg-positive-subtle", bundle: .lemonade) }
    var bgDefault: Color { Color("lemonade-background-bg-default", bundle: .lemonade) }
    var bgCritical: Color { Color("lemonade-background-voice-bg-critical", bundle: .lemonade) }
    var bgBrandHigh: Color { Color("lemonade-background-brand-bg-brand-high", bundle: .lemonade) }
    var bgCaution: Color { Color("lemonade-background-voice-bg-caution", bundle: .lemonade) }
    var bgBrand: Color { Color("lemonade-background-brand-bg-brand", bundle: .lemonade) }
    var bgElevated: Color { Color("lemonade-background-bg-elevated", bundle: .lemonade) }
    var bgElevatedInverse: Color { Color("lemonade-background-inverse-bg-elevated-inverse", bundle: .lemonade) }
    var bgSubtle: Color { Color("lemonade-background-bg-subtle", bundle: .lemonade) }
    var bgInfo: Color { Color("lemonade-background-voice-bg-info", bundle: .lemonade) }
    var bgPositive: Color { Color("lemonade-background-voice-bg-positive", bundle: .lemonade) }
    var bgInfoSubtle: Color { Color("lemonade-background-voice-bg-info-subtle", bundle: .lemonade) }
    var bgElevatedHigh: Color { Color("lemonade-background-bg-elevated-high", bundle: .lemonade) }
}

/// Adaptive theme implementation — colors resolve automatically via Asset Catalog
public struct LemonadeAdaptiveTheme: LemonadeSemanticColors {
    public init() {}

    public let interaction: InteractionColors = AdaptiveInteractionColors()
    public let border: BorderColors = AdaptiveBorderColors()
    public let content: ContentColors = AdaptiveContentColors()
    public let background: BackgroundColors = AdaptiveBackgroundColors()
}
