import SwiftUI

/// Lemonade Design System Font Weight tokens.
/// Maps design token weights to SwiftUI Font.Weight values.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-typography-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-typography-token-converter.main.kts
///  
///  @generated by scripts/swiftui-typography-token-converter.main.kts
/// 

/// Font weight token enum
public enum LemonadeFontWeights {
    case bold
    case semibold
    case medium
    case regular

    /// Returns the Font.Weight value for this font weight token
    public var value: Font.Weight {
        switch self {
        case .bold: return .bold
        case .semibold: return .semibold
        case .medium: return .medium
        case .regular: return .regular
        }
    }
}

/// Protocol for font weight values
public protocol LemonadeFontWeightValues {
    var bold: Font.Weight { get }
    var semibold: Font.Weight { get }
    var medium: Font.Weight { get }
    var regular: Font.Weight { get }
}

/// Default font weight values implementation
public struct LemonadeFontWeightValuesImpl: LemonadeFontWeightValues {
    public let bold: Font.Weight = LemonadeFontWeights.bold.value
    public let semibold: Font.Weight = LemonadeFontWeights.semibold.value
    public let medium: Font.Weight = LemonadeFontWeights.medium.value
    public let regular: Font.Weight = LemonadeFontWeights.regular.value

    public init() {}
}
