import SwiftUI

/// Primitive color system from Lemonade DS - Foundations
/// Supports both solid and alpha color variants
/// Using floating-point RGBA values for precision
/// See [Lemonade colors](https://www.figma.com/design/3DI1AqqkYgRJgYCjOXjbDO/Review-and-update-colors?node-id=97-4923)
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-color-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-color-token-converter.main.kts
///  
///  @generated by scripts/swiftui-color-token-converter.main.kts
/// 

/// Internal API - Use LemonadeTheme instead of accessing colors directly
public enum LemonadePrimitiveColors {
    public enum Solid {
        public enum YellowLime {
            public static let yellowLime900: Color = Color(
                red: 0.1595725,
                green: 0.1941985,
                blue: 0.0458015,
                opacity: 1.0000000
            )
            public static let yellowLime600: Color = Color(
                red: 0.7802666,
                green: 0.7920000,
                blue: 0.0880000,
                opacity: 1.0000000
            )
            public static let yellowLime400: Color = Color(
                red: 0.9160000,
                green: 0.9160000,
                blue: 0.2840000,
                opacity: 1.0000000
            )
            public static let yellowLime300: Color = Color(
                red: 0.9480000,
                green: 0.9480000,
                blue: 0.5320000,
                opacity: 1.0000000
            )
            public static let yellowLime200: Color = Color(
                red: 0.9677966,
                green: 0.9677966,
                blue: 0.6522034,
                opacity: 1.0000000
            )
            public static let yellowLime800: Color = Color(
                red: 0.2726780,
                green: 0.3205442,
                blue: 0.0594558,
                opacity: 1.0000000
            )
            public static let yellowLime100: Color = Color(
                red: 0.9803922,
                green: 0.9803922,
                blue: 0.7803922,
                opacity: 1.0000000
            )
            public static let yellowLime700: Color = Color(
                red: 0.4264000,
                green: 0.4680000,
                blue: 0.0520000,
                opacity: 1.0000000
            )
            public static let yellowLime500: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 1.0000000
            )
            public static let yellowLime50: Color = Color(
                red: 0.9882353,
                green: 0.9882353,
                blue: 0.9176471,
                opacity: 1.0000000
            )
            public static let yellowLime950: Color = Color(
                red: 0.1160000,
                green: 0.1550000,
                blue: 0.0250000,
                opacity: 1.0000000
            )
        }
        public enum White {
            public static let white800: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.8000000
            )
            public static let white700: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.7000000
            )
            public static let white500: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.5000000
            )
            public static let white400: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.4000000
            )
            public static let white50: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.0500000
            )
            public static let white600: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.6000000
            )
            public static let white300: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.3000000
            )
            public static let white950: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let white900: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.9000000
            )
            public static let white100: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.1000000
            )
            public static let white200: Color = Color(
                red: 1.0000000,
                green: 1.0000000,
                blue: 1.0000000,
                opacity: 0.2000000
            )
        }
        public enum Amber {
            public static let amber900: Color = Color(
                red: 0.4804463,
                green: 0.1997653,
                blue: 0.0248332,
                opacity: 1.0000000
            )
            public static let amber800: Color = Color(
                red: 0.5903065,
                green: 0.2337568,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let amber700: Color = Color(
                red: 0.7317888,
                green: 0.3010233,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let amber200: Color = Color(
                red: 0.9957299,
                green: 0.9012048,
                blue: 0.5221892,
                opacity: 1.0000000
            )
            public static let amber100: Color = Color(
                red: 0.9969999,
                green: 0.9530826,
                blue: 0.7775240,
                opacity: 1.0000000
            )
            public static let amber600: Color = Color(
                red: 0.8837689,
                green: 0.4433509,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let amber300: Color = Color(
                red: 1.0000000,
                green: 0.8238499,
                blue: 0.1876057,
                opacity: 1.0000000
            )
            public static let amber500: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let amber400: Color = Color(
                red: 0.9930035,
                green: 0.7819446,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let amber50: Color = Color(
                red: 1.0000000,
                green: 0.9845064,
                blue: 0.9199941,
                opacity: 1.0000000
            )
            public static let amber950: Color = Color(
                red: 0.2740671,
                green: 0.0984927,
                blue: 0.0046668,
                opacity: 1.0000000
            )
        }
        public enum Orange {
            public static let orange900: Color = Color(
                red: 0.4951185,
                green: 0.1654189,
                blue: 0.0456523,
                opacity: 1.0000000
            )
            public static let orange800: Color = Color(
                red: 0.6244982,
                green: 0.1766332,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let orange700: Color = Color(
                red: 0.7918817,
                green: 0.2072699,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let orange600: Color = Color(
                red: 0.9607055,
                green: 0.2881908,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let orange500: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let orange400: Color = Color(
                red: 1.0000000,
                green: 0.5370231,
                blue: 0.0138416,
                opacity: 1.0000000
            )
            public static let orange200: Color = Color(
                red: 1.0000000,
                green: 0.8411152,
                blue: 0.6568335,
                opacity: 1.0000000
            )
            public static let orange300: Color = Color(
                red: 1.0000000,
                green: 0.7222757,
                blue: 0.4139271,
                opacity: 1.0000000
            )
            public static let orange100: Color = Color(
                red: 1.0000000,
                green: 0.9288763,
                blue: 0.8325849,
                opacity: 1.0000000
            )
            public static let orange50: Color = Color(
                red: 1.0000000,
                green: 0.9690531,
                blue: 0.9292630,
                opacity: 1.0000000
            )
            public static let orange950: Color = Color(
                red: 0.2664344,
                green: 0.0744110,
                blue: 0.0219054,
                opacity: 1.0000000
            )
        }
        public enum Pink {
            public static let pink200: Color = Color(
                red: 0.9876744,
                green: 0.8090493,
                blue: 0.9107284,
                opacity: 1.0000000
            )
            public static let pink300: Color = Color(
                red: 0.9940834,
                green: 0.6464798,
                blue: 0.8371422,
                opacity: 1.0000000
            )
            public static let pink100: Color = Color(
                red: 0.9886688,
                green: 0.9052760,
                blue: 0.9529447,
                opacity: 1.0000000
            )
            public static let pink900: Color = Color(
                red: 0.5251818,
                green: 0.0632824,
                blue: 0.2613340,
                opacity: 1.0000000
            )
            public static let pink800: Color = Color(
                red: 0.6386032,
                green: 0.0000000,
                blue: 0.2980438,
                opacity: 1.0000000
            )
            public static let pink700: Color = Color(
                red: 0.7777568,
                green: 0.0000000,
                blue: 0.3589230,
                opacity: 1.0000000
            )
            public static let pink600: Color = Color(
                red: 0.9013361,
                green: 0.0000000,
                blue: 0.4634101,
                opacity: 1.0000000
            )
            public static let pink500: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 1.0000000
            )
            public static let pink400: Color = Color(
                red: 0.9856091,
                green: 0.3920409,
                blue: 0.7138621,
                opacity: 1.0000000
            )
            public static let pink50: Color = Color(
                red: 0.9913175,
                green: 0.9486182,
                blue: 0.9719059,
                opacity: 1.0000000
            )
            public static let pink950: Color = Color(
                red: 0.3180017,
                green: 0.0150837,
                blue: 0.1398192,
                opacity: 1.0000000
            )
        }
        public enum Neutral {
            public static let neutral600: Color = Color(
                red: 0.3333333,
                green: 0.3294118,
                blue: 0.3137255,
                opacity: 1.0000000
            )
            public static let neutral100: Color = Color(
                red: 0.9637647,
                green: 0.9604706,
                blue: 0.9538823,
                opacity: 1.0000000
            )
            public static let neutral400: Color = Color(
                red: 0.6500393,
                green: 0.6419216,
                blue: 0.6283922,
                opacity: 1.0000000
            )
            public static let neutral300: Color = Color(
                red: 0.8413529,
                green: 0.8311176,
                blue: 0.8174706,
                opacity: 1.0000000
            )
            public static let neutral200: Color = Color(
                red: 0.9137255,
                green: 0.9058824,
                blue: 0.8901961,
                opacity: 1.0000000
            )
            public static let neutral500: Color = Color(
                red: 0.5028824,
                green: 0.4945126,
                blue: 0.4735883,
                opacity: 1.0000000
            )
            public static let neutral700: Color = Color(
                red: 0.2588235,
                green: 0.2549020,
                blue: 0.2431373,
                opacity: 1.0000000
            )
            public static let neutral800: Color = Color(
                red: 0.1568628,
                green: 0.1529412,
                blue: 0.1450980,
                opacity: 1.0000000
            )
            public static let neutral900: Color = Color(
                red: 0.1040000,
                green: 0.1017333,
                blue: 0.0960000,
                opacity: 1.0000000
            )
            public static let neutral50: Color = Color(
                red: 0.9747059,
                green: 0.9714118,
                blue: 0.9664706,
                opacity: 1.0000000
            )
            public static let neutral950: Color = Color(
                red: 0.0431373,
                green: 0.0421569,
                blue: 0.0392157,
                opacity: 1.0000000
            )
        }
        public enum Red {
            public static let red300: Color = Color(
                red: 1.0000000,
                green: 0.6346798,
                blue: 0.6363715,
                opacity: 1.0000000
            )
            public static let red100: Color = Color(
                red: 0.9993008,
                green: 0.8856429,
                blue: 0.8856770,
                opacity: 1.0000000
            )
            public static let red700: Color = Color(
                red: 0.7568847,
                green: 0.0000000,
                blue: 0.0287545,
                opacity: 1.0000000
            )
            public static let red900: Color = Color(
                red: 0.5091705,
                green: 0.0923288,
                blue: 0.1006870,
                opacity: 1.0000000
            )
            public static let red400: Color = Color(
                red: 1.0000000,
                green: 0.3911527,
                blue: 0.4038569,
                opacity: 1.0000000
            )
            public static let red800: Color = Color(
                red: 0.6222082,
                green: 0.0287906,
                blue: 0.0689382,
                opacity: 1.0000000
            )
            public static let red500: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 1.0000000
            )
            public static let red600: Color = Color(
                red: 0.9064575,
                green: 0.0000000,
                blue: 0.0422148,
                opacity: 1.0000000
            )
            public static let red200: Color = Color(
                red: 1.0000000,
                green: 0.7898434,
                blue: 0.7900283,
                opacity: 1.0000000
            )
            public static let red50: Color = Color(
                red: 0.9968413,
                green: 0.9495854,
                blue: 0.9495857,
                opacity: 1.0000000
            )
            public static let red950: Color = Color(
                red: 0.2753967,
                green: 0.0315932,
                blue: 0.0344976,
                opacity: 1.0000000
            )
        }
        public enum Cyan {
            public static let cyan500: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 1.0000000
            )
            public static let cyan900: Color = Color(
                red: 0.0637282,
                green: 0.3067086,
                blue: 0.3937417,
                opacity: 1.0000000
            )
            public static let cyan300: Color = Color(
                red: 0.3266667,
                green: 0.9169948,
                blue: 0.9913582,
                opacity: 1.0000000
            )
            public static let cyan200: Color = Color(
                red: 0.6366476,
                green: 0.9554243,
                blue: 0.9921554,
                opacity: 1.0000000
            )
            public static let cyan100: Color = Color(
                red: 0.8092722,
                green: 0.9805906,
                blue: 0.9965361,
                opacity: 1.0000000
            )
            public static let cyan400: Color = Color(
                red: 0.0000000,
                green: 0.8273619,
                blue: 0.9509647,
                opacity: 1.0000000
            )
            public static let cyan600: Color = Color(
                red: 0.0000000,
                green: 0.5741973,
                blue: 0.7225724,
                opacity: 1.0000000
            )
            public static let cyan800: Color = Color(
                red: 0.0000000,
                green: 0.3711744,
                blue: 0.4712479,
                opacity: 1.0000000
            )
            public static let cyan700: Color = Color(
                red: 0.0000000,
                green: 0.4590370,
                blue: 0.5832522,
                opacity: 1.0000000
            )
            public static let cyan50: Color = Color(
                red: 0.9250038,
                green: 0.9960225,
                blue: 0.9999692,
                opacity: 1.0000000
            )
            public static let cyan950: Color = Color(
                red: 0.0211879,
                green: 0.2006471,
                blue: 0.2698321,
                opacity: 1.0000000
            )
        }
        public enum Purple {
            public static let purple700: Color = Color(
                red: 0.5099057,
                green: 0.0000000,
                blue: 0.8572577,
                opacity: 1.0000000
            )
            public static let purple800: Color = Color(
                red: 0.4299934,
                green: 0.0666391,
                blue: 0.6907452,
                opacity: 1.0000000
            )
            public static let purple600: Color = Color(
                red: 0.5968394,
                green: 0.0617293,
                blue: 0.9813578,
                opacity: 1.0000000
            )
            public static let purple400: Color = Color(
                red: 0.7595677,
                green: 0.4798001,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let purple500: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let purple200: Color = Color(
                red: 0.9150137,
                green: 0.8330874,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let purple900: Color = Color(
                red: 0.3507220,
                green: 0.0873005,
                blue: 0.5451928,
                opacity: 1.0000000
            )
            public static let purple300: Color = Color(
                red: 0.8544052,
                green: 0.6977942,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let purple100: Color = Color(
                red: 0.9525601,
                green: 0.9090819,
                blue: 0.9999775,
                opacity: 1.0000000
            )
            public static let purple50: Color = Color(
                red: 0.9804397,
                green: 0.9611090,
                blue: 0.9997747,
                opacity: 1.0000000
            )
            public static let purple950: Color = Color(
                red: 0.2000000,
                green: 0.0274510,
                blue: 0.3490196,
                opacity: 1.0000000
            )
        }
        public enum Rose {
            public static let rose900: Color = Color(
                red: 0.5445029,
                green: 0.0300387,
                blue: 0.2106990,
                opacity: 1.0000000
            )
            public static let rose700: Color = Color(
                red: 0.7785064,
                green: 0.0000000,
                blue: 0.2106963,
                opacity: 1.0000000
            )
            public static let rose600: Color = Color(
                red: 0.9273909,
                green: 0.0000000,
                blue: 0.2487093,
                opacity: 1.0000000
            )
            public static let rose400: Color = Color(
                red: 1.0000000,
                green: 0.3888606,
                blue: 0.4943316,
                opacity: 1.0000000
            )
            public static let rose200: Color = Color(
                red: 1.0000000,
                green: 0.8011076,
                blue: 0.8256558,
                opacity: 1.0000000
            )
            public static let rose300: Color = Color(
                red: 1.0000000,
                green: 0.6299288,
                blue: 0.6795161,
                opacity: 1.0000000
            )
            public static let rose800: Color = Color(
                red: 0.6466910,
                green: 0.0000000,
                blue: 0.2116680,
                opacity: 1.0000000
            )
            public static let rose500: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 1.0000000
            )
            public static let rose100: Color = Color(
                red: 1.0000000,
                green: 0.8934202,
                blue: 0.9013287,
                opacity: 1.0000000
            )
            public static let rose50: Color = Color(
                red: 0.9990231,
                green: 0.9447284,
                blue: 0.9486037,
                opacity: 1.0000000
            )
            public static let rose950: Color = Color(
                red: 0.3031470,
                green: 0.0088198,
                blue: 0.0958587,
                opacity: 1.0000000
            )
        }
        public enum Black {
            public static let black900: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.9000000
            )
            public static let black950: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let black300: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.3000000
            )
            public static let black600: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.6000000
            )
            public static let black800: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.8000000
            )
            public static let black400: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.4000000
            )
            public static let black50: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.0500000
            )
            public static let black500: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.5000000
            )
            public static let black200: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.2000000
            )
            public static let black100: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.1000000
            )
            public static let black700: Color = Color(
                red: 0.0000000,
                green: 0.0000000,
                blue: 0.0000000,
                opacity: 0.7000000
            )
        }
        public enum Green {
            public static let green800: Color = Color(
                red: 0.0057959,
                green: 0.4014766,
                blue: 0.1885885,
                opacity: 1.0000000
            )
            public static let green700: Color = Color(
                red: 0.0000000,
                green: 0.5099977,
                blue: 0.2098097,
                opacity: 1.0000000
            )
            public static let green200: Color = Color(
                red: 0.7250790,
                green: 0.9712607,
                blue: 0.8118365,
                opacity: 1.0000000
            )
            public static let green400: Color = Color(
                red: 0.0198698,
                green: 0.8753123,
                blue: 0.4485098,
                opacity: 1.0000000
            )
            public static let green300: Color = Color(
                red: 0.4814550,
                green: 0.9463489,
                blue: 0.6570023,
                opacity: 1.0000000
            )
            public static let green600: Color = Color(
                red: 0.0000000,
                green: 0.6513023,
                blue: 0.2419927,
                opacity: 1.0000000
            )
            public static let green500: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 1.0000000
            )
            public static let green900: Color = Color(
                red: 0.0511253,
                green: 0.3286888,
                blue: 0.1701725,
                opacity: 1.0000000
            )
            public static let green100: Color = Color(
                red: 0.8608796,
                green: 0.9882110,
                blue: 0.9046972,
                opacity: 1.0000000
            )
            public static let green50: Color = Color(
                red: 0.9413932,
                green: 0.9922020,
                blue: 0.9570248,
                opacity: 1.0000000
            )
            public static let green950: Color = Color(
                red: 0.0119957,
                green: 0.1810015,
                blue: 0.0835036,
                opacity: 1.0000000
            )
        }
        public enum Teal {
            public static let teal900: Color = Color(
                red: 0.0420031,
                green: 0.3081708,
                blue: 0.2917560,
                opacity: 1.0000000
            )
            public static let teal800: Color = Color(
                red: 0.0000000,
                green: 0.3731433,
                blue: 0.3521347,
                opacity: 1.0000000
            )
            public static let teal600: Color = Color(
                red: 0.0000000,
                green: 0.5892683,
                blue: 0.5372885,
                opacity: 1.0000000
            )
            public static let teal500: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 1.0000000
            )
            public static let teal400: Color = Color(
                red: 0.0000000,
                green: 0.8352504,
                blue: 0.7433177,
                opacity: 1.0000000
            )
            public static let teal300: Color = Color(
                red: 0.2756204,
                green: 0.9274332,
                blue: 0.8335048,
                opacity: 1.0000000
            )
            public static let teal200: Color = Color(
                red: 0.5870301,
                green: 0.9674543,
                blue: 0.8945857,
                opacity: 1.0000000
            )
            public static let teal100: Color = Color(
                red: 0.7967792,
                green: 0.9858463,
                blue: 0.9457266,
                opacity: 1.0000000
            )
            public static let teal700: Color = Color(
                red: 0.0000000,
                green: 0.4689988,
                blue: 0.4349717,
                opacity: 1.0000000
            )
            public static let teal50: Color = Color(
                red: 0.9422644,
                green: 0.9925186,
                blue: 0.9809169,
                opacity: 1.0000000
            )
            public static let teal950: Color = Color(
                red: 0.0081214,
                green: 0.1847564,
                blue: 0.1808228,
                opacity: 1.0000000
            )
        }
        public enum Blue {
            public static let blue100: Color = Color(
                red: 0.8582405,
                green: 0.9178275,
                blue: 0.9972706,
                opacity: 1.0000000
            )
            public static let blue400: Color = Color(
                red: 0.3157993,
                green: 0.6355904,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let blue900: Color = Color(
                red: 0.1090559,
                green: 0.2221926,
                blue: 0.5575137,
                opacity: 1.0000000
            )
            public static let blue300: Color = Color(
                red: 0.5565923,
                green: 0.7731643,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let blue800: Color = Color(
                red: 0.0997812,
                green: 0.2337701,
                blue: 0.7229224,
                opacity: 1.0000000
            )
            public static let blue600: Color = Color(
                red: 0.0836191,
                green: 0.3644171,
                blue: 0.9863431,
                opacity: 1.0000000
            )
            public static let blue700: Color = Color(
                red: 0.0779077,
                green: 0.2791352,
                blue: 0.9017745,
                opacity: 1.0000000
            )
            public static let blue200: Color = Color(
                red: 0.7450930,
                green: 0.8586638,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let blue500: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let blue50: Color = Color(
                red: 0.9369398,
                green: 0.9640346,
                blue: 0.9988720,
                opacity: 1.0000000
            )
            public static let blue950: Color = Color(
                red: 0.0872626,
                green: 0.1431323,
                blue: 0.3356921,
                opacity: 1.0000000
            )
        }
        public enum Yellow {
            public static let yellow900: Color = Color(
                red: 0.4504862,
                green: 0.2424023,
                blue: 0.0409038,
                opacity: 1.0000000
            )
            public static let yellow800: Color = Color(
                red: 0.5359094,
                green: 0.2927127,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let yellow600: Color = Color(
                red: 0.8175541,
                green: 0.5296360,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let yellow300: Color = Color(
                red: 1.0000000,
                green: 0.8762567,
                blue: 0.1257126,
                opacity: 1.0000000
            )
            public static let yellow200: Color = Color(
                red: 0.9986842,
                green: 0.9411308,
                blue: 0.5228281,
                opacity: 1.0000000
            )
            public static let yellow400: Color = Color(
                red: 0.9930035,
                green: 0.7819446,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let yellow100: Color = Color(
                red: 0.9969828,
                green: 0.9767838,
                blue: 0.7597213,
                opacity: 1.0000000
            )
            public static let yellow500: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let yellow700: Color = Color(
                red: 0.6510636,
                green: 0.3732094,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let yellow50: Color = Color(
                red: 0.9955702,
                green: 0.9878028,
                blue: 0.9100786,
                opacity: 1.0000000
            )
            public static let yellow950: Color = Color(
                red: 0.2618610,
                green: 0.1240003,
                blue: 0.0174206,
                opacity: 1.0000000
            )
        }
        public enum Indigo {
            public static let indigo800: Color = Color(
                red: 0.2154269,
                green: 0.1632234,
                blue: 0.6737074,
                opacity: 1.0000000
            )
            public static let indigo600: Color = Color(
                red: 0.3108855,
                green: 0.2244045,
                blue: 0.9662613,
                opacity: 1.0000000
            )
            public static let indigo500: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo400: Color = Color(
                red: 0.4878469,
                green: 0.5265173,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo300: Color = Color(
                red: 0.6391280,
                green: 0.7021305,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo100: Color = Color(
                red: 0.8779963,
                green: 0.9058983,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo700: Color = Color(
                red: 0.2643530,
                green: 0.1765924,
                blue: 0.8448341,
                opacity: 1.0000000
            )
            public static let indigo200: Color = Color(
                red: 0.7783517,
                green: 0.8231921,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo900: Color = Color(
                red: 0.1916484,
                green: 0.1726452,
                blue: 0.5226694,
                opacity: 1.0000000
            )
            public static let indigo50: Color = Color(
                red: 0.9333945,
                green: 0.9491386,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let indigo950: Color = Color(
                red: 0.1171338,
                green: 0.1026302,
                blue: 0.3006192,
                opacity: 1.0000000
            )
        }
        public enum GreenLime {
            public static let greenLime50: Color = Color(
                red: 0.9690421,
                green: 0.9965203,
                blue: 0.9062311,
                opacity: 1.0000000
            )
            public static let greenLime100: Color = Color(
                red: 0.9250763,
                green: 0.9888007,
                blue: 0.7933732,
                opacity: 1.0000000
            )
            public static let greenLime200: Color = Color(
                red: 0.8477643,
                green: 0.9783047,
                blue: 0.5999010,
                opacity: 1.0000000
            )
            public static let greenLime300: Color = Color(
                red: 0.7329368,
                green: 0.9551595,
                blue: 0.3178042,
                opacity: 1.0000000
            )
            public static let greenLime400: Color = Color(
                red: 0.6024434,
                green: 0.9016712,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let greenLime500: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let greenLime600: Color = Color(
                red: 0.3687201,
                green: 0.6474891,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let greenLime700: Color = Color(
                red: 0.2848082,
                green: 0.4915021,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let greenLime800: Color = Color(
                red: 0.2372255,
                green: 0.3880722,
                blue: 0.0000000,
                opacity: 1.0000000
            )
            public static let greenLime900: Color = Color(
                red: 0.2070180,
                green: 0.3272238,
                blue: 0.0552370,
                opacity: 1.0000000
            )
            public static let greenLime950: Color = Color(
                red: 0.0990861,
                green: 0.1812896,
                blue: 0.0109399,
                opacity: 1.0000000
            )
        }
        public enum Violet {
            public static let violet50: Color = Color(
                red: 0.9605924,
                green: 0.9527793,
                blue: 0.9996636,
                opacity: 1.0000000
            )
            public static let violet100: Color = Color(
                red: 0.9290421,
                green: 0.9130082,
                blue: 0.9970685,
                opacity: 1.0000000
            )
            public static let violet200: Color = Color(
                red: 0.8665415,
                green: 0.8378735,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let violet300: Color = Color(
                red: 0.7700671,
                green: 0.7039360,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let violet400: Color = Color(
                red: 0.6526055,
                green: 0.5169347,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let violet500: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 1.0000000
            )
            public static let violet600: Color = Color(
                red: 0.4999112,
                green: 0.1337047,
                blue: 0.9959983,
                opacity: 1.0000000
            )
            public static let violet700: Color = Color(
                red: 0.4396859,
                green: 0.0314230,
                blue: 0.9064206,
                opacity: 1.0000000
            )
            public static let violet800: Color = Color(
                red: 0.3653835,
                green: 0.0555390,
                blue: 0.7533063,
                opacity: 1.0000000
            )
            public static let violet900: Color = Color(
                red: 0.3024733,
                green: 0.0891159,
                blue: 0.6037157,
                opacity: 1.0000000
            )
            public static let violet950: Color = Color(
                red: 0.1825469,
                green: 0.0509022,
                blue: 0.4063526,
                opacity: 1.0000000
            )
        }
    }

    public enum Alpha {
        public enum Neutral {
            public static let alpha900: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.9000000
            )
            public static let alpha700: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.7000000
            )
            public static let alpha600: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.6000000
            )
            public static let alpha300: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.3000000
            )
            public static let alpha200: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.2000000
            )
            public static let alpha500: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.5000000
            )
            public static let alpha800: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.8000000
            )
            public static let alpha100: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.1000000
            )
            public static let alpha400: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.4000000
            )
            public static let alpha50: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.0500000
            )
            public static let alpha950: Color = Color(
                red: 0.1058824,
                green: 0.1019608,
                blue: 0.0941176,
                opacity: 0.9500000
            )
        }
        public enum Yellow {
            public static let alpha50: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.9413120,
                green: 0.6929154,
                blue: 0.0000000,
                opacity: 0.9500000
            )
        }
        public enum Amber {
            public static let alpha50: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.9942715,
                green: 0.6020927,
                blue: 0.0000000,
                opacity: 0.9500000
            )
        }
        public enum Orange {
            public static let alpha50: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 1.0000000,
                green: 0.4107343,
                blue: 0.0000000,
                opacity: 0.9500000
            )
        }
        public enum Red {
            public static let alpha50: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.9826614,
                green: 0.1717971,
                blue: 0.2130703,
                opacity: 0.9500000
            )
        }
        public enum Rose {
            public static let alpha50: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 1.0000000,
                green: 0.1246152,
                blue: 0.3390034,
                opacity: 0.9500000
            )
        }
        public enum Pink {
            public static let alpha50: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.9658055,
                green: 0.1981388,
                blue: 0.6043244,
                opacity: 0.9500000
            )
        }
        public enum Purple {
            public static let alpha50: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.6779096,
                green: 0.2759419,
                blue: 1.0000000,
                opacity: 0.9500000
            )
        }
        public enum Violet {
            public static let alpha50: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.5568628,
                green: 0.3176471,
                blue: 1.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.5568628,
                green: 0.3176471,
                blue: 1.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.5559263,
                green: 0.3181638,
                blue: 1.0000000,
                opacity: 0.9500000
            )
        }
        public enum Indigo {
            public static let alpha50: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.3821761,
                green: 0.3718883,
                blue: 1.0000000,
                opacity: 0.9500000
            )
        }
        public enum Blue {
            public static let alpha50: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.1686275,
                green: 0.4980392,
                blue: 1.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.1686275,
                green: 0.4980392,
                blue: 1.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.1693325,
                green: 0.4980495,
                blue: 1.0000000,
                opacity: 0.9500000
            )
        }
        public enum Cyan {
            public static let alpha50: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.0000000,
                green: 0.7218724,
                blue: 0.8573381,
                opacity: 0.9500000
            )
        }
        public enum Teal {
            public static let alpha50: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.0000000,
                green: 0.7333587,
                blue: 0.6548709,
                opacity: 0.9500000
            )
        }
        public enum Green {
            public static let alpha50: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.0000000,
                green: 0.7871556,
                blue: 0.3156219,
                opacity: 0.9500000
            )
        }
        public enum GreenLime {
            public static let alpha50: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.4872932,
                green: 0.8099174,
                blue: 0.0000000,
                opacity: 0.9500000
            )
        }
        public enum YellowLime {
            public static let alpha50: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.0500000
            )
            public static let alpha100: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.1000000
            )
            public static let alpha200: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.2000000
            )
            public static let alpha300: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.3000000
            )
            public static let alpha400: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.4000000
            )
            public static let alpha500: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.5000000
            )
            public static let alpha600: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.6000000
            )
            public static let alpha700: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.7000000
            )
            public static let alpha800: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.8000000
            )
            public static let alpha900: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.9000000
            )
            public static let alpha950: Color = Color(
                red: 0.8823529,
                green: 0.8980392,
                blue: 0.1019608,
                opacity: 0.9500000
            )
        }
    }
}
