import SwiftUI

/// Lemonade Design System Line Height tokens.
/// Provides a consistent way to manage line heights across interfaces.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-typography-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-typography-token-converter.main.kts
///  
///  @generated by scripts/swiftui-typography-token-converter.main.kts
/// 

/// Line height token enum
public enum LemonadeLineHeights {
    case lineHeight250
    case lineHeight300
    case lineHeight350
    case lineHeight400
    case lineHeight450
    case lineHeight500
    case lineHeight600
    case lineHeight650
    case lineHeight700
    case lineHeight800
    case lineHeight900
    case lineHeight1000
    case lineHeight1100
    case lineHeight1200
    case lineHeight1400
    case lineHeight1600
    case lineHeight1800
    case lineHeight2000

    /// Returns the CGFloat value for this line height token
    public var value: CGFloat {
        switch self {
        case .lineHeight250: return 10
        case .lineHeight300: return 12
        case .lineHeight350: return 14
        case .lineHeight400: return 16
        case .lineHeight450: return 18
        case .lineHeight500: return 20
        case .lineHeight600: return 24
        case .lineHeight650: return 26
        case .lineHeight700: return 28
        case .lineHeight800: return 32
        case .lineHeight900: return 36
        case .lineHeight1000: return 40
        case .lineHeight1100: return 44
        case .lineHeight1200: return 48
        case .lineHeight1400: return 56
        case .lineHeight1600: return 64
        case .lineHeight1800: return 72
        case .lineHeight2000: return 80
        }
    }
}

/// Protocol for line height values
public protocol LemonadeLineHeightValues {
    var lineHeight250: CGFloat { get }
    var lineHeight300: CGFloat { get }
    var lineHeight350: CGFloat { get }
    var lineHeight400: CGFloat { get }
    var lineHeight450: CGFloat { get }
    var lineHeight500: CGFloat { get }
    var lineHeight600: CGFloat { get }
    var lineHeight650: CGFloat { get }
    var lineHeight700: CGFloat { get }
    var lineHeight800: CGFloat { get }
    var lineHeight900: CGFloat { get }
    var lineHeight1000: CGFloat { get }
    var lineHeight1100: CGFloat { get }
    var lineHeight1200: CGFloat { get }
    var lineHeight1400: CGFloat { get }
    var lineHeight1600: CGFloat { get }
    var lineHeight1800: CGFloat { get }
    var lineHeight2000: CGFloat { get }
}

/// Default line height values implementation
public struct LemonadeLineHeightValuesImpl: LemonadeLineHeightValues {
    public let lineHeight250: CGFloat = LemonadeLineHeights.lineHeight250.value
    public let lineHeight300: CGFloat = LemonadeLineHeights.lineHeight300.value
    public let lineHeight350: CGFloat = LemonadeLineHeights.lineHeight350.value
    public let lineHeight400: CGFloat = LemonadeLineHeights.lineHeight400.value
    public let lineHeight450: CGFloat = LemonadeLineHeights.lineHeight450.value
    public let lineHeight500: CGFloat = LemonadeLineHeights.lineHeight500.value
    public let lineHeight600: CGFloat = LemonadeLineHeights.lineHeight600.value
    public let lineHeight650: CGFloat = LemonadeLineHeights.lineHeight650.value
    public let lineHeight700: CGFloat = LemonadeLineHeights.lineHeight700.value
    public let lineHeight800: CGFloat = LemonadeLineHeights.lineHeight800.value
    public let lineHeight900: CGFloat = LemonadeLineHeights.lineHeight900.value
    public let lineHeight1000: CGFloat = LemonadeLineHeights.lineHeight1000.value
    public let lineHeight1100: CGFloat = LemonadeLineHeights.lineHeight1100.value
    public let lineHeight1200: CGFloat = LemonadeLineHeights.lineHeight1200.value
    public let lineHeight1400: CGFloat = LemonadeLineHeights.lineHeight1400.value
    public let lineHeight1600: CGFloat = LemonadeLineHeights.lineHeight1600.value
    public let lineHeight1800: CGFloat = LemonadeLineHeights.lineHeight1800.value
    public let lineHeight2000: CGFloat = LemonadeLineHeights.lineHeight2000.value

    public init() {}
}
