import SwiftUI

/// Lemonade Design Border Width tokens.
/// Sets a small, clear set of predefined border width values for UI elements to ensure
/// consistent, scalable borders across the product.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-border-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-border-token-converter.main.kts
///  
///  @generated by scripts/swiftui-border-token-converter.main.kts
/// 

/// Base border width values
public protocol BaseBorderWidth {
    var border0: CGFloat { get }
    var border25: CGFloat { get }
    var border50: CGFloat { get }
    var border75: CGFloat { get }
    var border100: CGFloat { get }
}

/// State border width values
public protocol StateBorderWidth {
    var focusRing: CGFloat { get }
    var borderSelected: CGFloat { get }
}

/// Protocol defining border width categories
public protocol LemonadeBorderWidth {
    var base: BaseBorderWidth { get }
    var state: StateBorderWidth { get }
}

internal struct BaseBorderWidthImpl: BaseBorderWidth {
    let border0: CGFloat = 0
    let border25: CGFloat = 1
    let border50: CGFloat = 2
    let border75: CGFloat = 3
    let border100: CGFloat = 4
}

internal struct StateBorderWidthImpl: StateBorderWidth {
    let focusRing: CGFloat = 2
    let borderSelected: CGFloat = 2
}

/// Default border width implementation
public struct LemonadeBorderWidthTokens: LemonadeBorderWidth {
    public let base: BaseBorderWidth = BaseBorderWidthImpl()
    public let state: StateBorderWidth = StateBorderWidthImpl()

    public init() {}
}
