import SwiftUI

/// Semantic color tokens from Lemonade DS - Foundations
/// Organized by usage categories: Background, Content, Border, and Interaction
/// These tokens map to primitive colors and provide semantic meaning for UI elements
/// See [Lemonade semantic colors](https://www.figma.com/design/3DI1AqqkYgRJgYCjOXjbDO/Review-and-update-colors?node-id=97-4923)
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/swiftui-theme-token-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/swiftui-theme-token-converter.main.kts
///  
///  @generated by scripts/swiftui-theme-token-converter.main.kts
/// 

/// Interaction color definitions
public protocol InteractionColors {
    var bgNeutralSubtleInteractive: Color { get }
    var bgPositiveSubtleInteractive: Color { get }
    var bgInfoSubtleInteractive: Color { get }
    var bgNeutralInteractive: Color { get }
    var bgBrandHighInteractive: Color { get }
    var bgDefaultInteractive: Color { get }
    var bgCautionInteractive: Color { get }
    var bgPositiveInteractive: Color { get }
    var bgSubtleInteractive: Color { get }
    var bgInfoInteractive: Color { get }
    var bgCautionSubtleInteractive: Color { get }
    var bgCriticalInteractive: Color { get }
    var bgBrandInteractive: Color { get }
    var bgElevatedInteractive: Color { get }
    var bgCriticalSubtleInteractive: Color { get }
    var bgDefaultPressed: Color { get }
    var bgSubtlePressed: Color { get }
    var bgElevatedPressed: Color { get }
    var bgBrandPressed: Color { get }
    var bgBrandHighPressed: Color { get }
    var bgCriticalPressed: Color { get }
    var bgCautionPressed: Color { get }
    var bgInfoPressed: Color { get }
    var bgPositivePressed: Color { get }
    var bgNeutralPressed: Color { get }
    var bgCriticalSubtlePressed: Color { get }
    var bgCautionSubtlePressed: Color { get }
    var bgInfoSubtlePressed: Color { get }
    var bgPositiveSubtlePressed: Color { get }
    var bgNeutralSubtlePressed: Color { get }
    var bgElevatedHighInteractive: Color { get }
    var bgBrandElevatedInteractive: Color { get }
    var bgBrandElevatedPressed: Color { get }
}

/// Border color definitions
public protocol BorderColors {
    var borderBrandInverse: Color { get }
    var borderSelectedInverse: Color { get }
    var borderNeutralMediumInverse: Color { get }
    var borderNeutralLowInverse: Color { get }
    var borderAlwaysDark: Color { get }
    var borderPositiveSubtle: Color { get }
    var borderInfoSubtle: Color { get }
    var borderCautionSubtle: Color { get }
    var borderCriticalSubtle: Color { get }
    var borderPositive: Color { get }
    var borderInfo: Color { get }
    var borderCaution: Color { get }
    var borderOnBrandMedium: Color { get }
    var borderBrand: Color { get }
    var borderSelected: Color { get }
    var borderOnBrandLow: Color { get }
    var borderOnBrandHigh: Color { get }
    var borderCritical: Color { get }
    var borderNeutralLow: Color { get }
    var borderNeutralMedium: Color { get }
    var borderAlwaysLight: Color { get }
    var borderNeutralHigh: Color { get }
    var borderNeutralHighInverse: Color { get }
    var borderAlwaysLightLow: Color { get }
    var borderAlwaysLightMedium: Color { get }
    var borderAlwaysLightHigh: Color { get }
    var borderAlwaysDarkLow: Color { get }
    var borderAlwaysDarkMedium: Color { get }
    var borderAlwaysDarkHigh: Color { get }
}

/// Content color definitions
public protocol ContentColors {
    var contentOnBrandLow: Color { get }
    var contentBrand: Color { get }
    var contentCaution: Color { get }
    var contentInfo: Color { get }
    var contentTertiary: Color { get }
    var contentAlwaysLight: Color { get }
    var contentSecondary: Color { get }
    var contentPrimaryInverse: Color { get }
    var contentPositive: Color { get }
    var contentTertiaryInverse: Color { get }
    var contentAlwaysDark: Color { get }
    var contentNeutral: Color { get }
    var contentBrandInverse: Color { get }
    var contentSecondaryInverse: Color { get }
    var contentCritical: Color { get }
    var contentOnBrandHigh: Color { get }
    var contentPrimary: Color { get }
    var contentCriticalOnColor: Color { get }
    var contentCautionOnColor: Color { get }
    var contentInfoOnColor: Color { get }
    var contentPositiveOnColor: Color { get }
    var contentNeutralOnColor: Color { get }
    var contentBrandHigh: Color { get }
}

/// Background color definitions
public protocol BackgroundColors {
    var bgAlwaysLight: Color { get }
    var bgAlwaysDark: Color { get }
    var bgDefaultInverse: Color { get }
    var bgNeutralSubtle: Color { get }
    var bgCautionSubtle: Color { get }
    var bgCriticalSubtle: Color { get }
    var bgNeutral: Color { get }
    var bgBrandSubtle: Color { get }
    var bgSubtleInverse: Color { get }
    var bgBrandElevated: Color { get }
    var bgPositiveSubtle: Color { get }
    var bgDefault: Color { get }
    var bgCritical: Color { get }
    var bgBrandHigh: Color { get }
    var bgCaution: Color { get }
    var bgBrand: Color { get }
    var bgElevated: Color { get }
    var bgElevatedInverse: Color { get }
    var bgSubtle: Color { get }
    var bgInfo: Color { get }
    var bgPositive: Color { get }
    var bgInfoSubtle: Color { get }
    var bgElevatedHigh: Color { get }
}

/// Protocol defining semantic color categories
public protocol LemonadeSemanticColors {
    var interaction: InteractionColors { get }
    var border: BorderColors { get }
    var content: ContentColors { get }
    var background: BackgroundColors { get }
}
