import Foundation

/// Lemonade Design System Brand Logos.
/// Brand logos are loaded from the asset catalog bundled with this module.
/// Use the LemonadeUi.BrandLogo component to display brand logos.
///
///  Auto-generated content.
///  
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  
///  This file is automatically generated by the scripts/svg-asset-converter.main.kts script.
///  All changes will be overwritten when the script is run again.
///  
///  To add updated content:
///  1. Add your file to the tokens/ directory
///  2. Run: kotlin scripts/svg-asset-converter.main.kts
///  
///  @generated by scripts/svg-asset-converter.main.kts
/// 

/// Brand logo token enum
public enum LemonadeBrandLogo: String, CaseIterable {
    case amazon = "amazon"
    case amex = "amex"
    case applePay = "apple-pay"
    case bancomat = "bancomat"
    case cartesBancaires = "cartes-bancaires"
    case diners = "diners"
    @available(*, deprecated, renamed: "diners")
    case dinners = "dinners"
    case discover = "discover"
    case edenred = "edenred"
    case genericMealOrHealthIssuer = "generic-meal-or-health-issuer"
    case girocard = "girocard"
    case googlePay = "google-pay"
    case jcb = "jcb"
    case mastercard = "mastercard"
    case mbWay = "mb-way"
    case multibanco = "multibanco"
    case nfcLogo = "nfc-logo"
    case pagoBancomat = "pago-bancomat"
    case pluxee = "pluxee"
    case sepa = "sepa"
    case sodexo = "sodexo"
    case unionpay = "unionpay"
    case visa = "visa"

    /// Name of this logo's image in the asset catalog.
    ///
    /// Deprecated aliases have no asset of their own and resolve to their replacement's,
    /// so the two can never drift apart. Kept separate from `rawValue`, which stays the
    /// entry's own name so that `init(rawValue:)` still accepts it.
    public var assetName: String {
        switch self {
        case .dinners: return "diners"
        default: return rawValue
        }
    }

    /// Swift cannot synthesise `CaseIterable` for an enum carrying `@available` on a
    /// case, so `allCases` is written out here.
    ///
    /// Deprecated aliases are omitted: each renders the same asset as its replacement,
    /// so listing both would show the logo twice in a gallery. The cases themselves stay
    /// usable - referencing one just warns and points at the replacement.
    public static var allCases: [LemonadeBrandLogo] {
        [
            .amazon,
            .amex,
            .applePay,
            .bancomat,
            .cartesBancaires,
            .diners,
            .discover,
            .edenred,
            .genericMealOrHealthIssuer,
            .girocard,
            .googlePay,
            .jcb,
            .mastercard,
            .mbWay,
            .multibanco,
            .nfcLogo,
            .pagoBancomat,
            .pluxee,
            .sepa,
            .sodexo,
            .unionpay,
            .visa,
        ]
    }
}
