import SwiftUI

/// Lemonade Design System Theme
/// Provides a centralized access point for all design system tokens.
///
/// Usage:
/// ```swift
/// // Access colors through the theme
/// Text("Hello")
///     .foregroundColor(LemonadeTheme.colors.background.primary)
///
/// // Access spacing
/// VStack(spacing: LemonadeTheme.spaces.spacing100) {
///     // content
/// }
/// ```
///
/// Auto-generated content.
///
/// ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///
/// This file is automatically generated by the design system scripts.
/// All changes will be overwritten when scripts are run again.

/// Main theme entry point for Lemonade Design System
public enum LemonadeTheme {
    /// Semantic color tokens
    public static let colors: LemonadeSemanticColors = LemonadeLightTheme()

    /// Spacing tokens
    public static let spaces: LemonadeSpaceValues = LemonadeSpaceValuesImpl()

    /// Radius tokens
    public static let radius: LemonadeRadiusValues = LemonadeRadiusValuesImpl()

    /// Shape tokens (rounded rectangles with predefined radii)
    public static let shapes: LemonadeShapes = LemonadeShapesImpl()

    /// Size tokens
    public static let sizes: LemonadeSizeValues = LemonadeSizeValuesImpl()

    /// Opacity tokens
    public static let opacity: LemonadeOpacity = LemonadeOpacityTokens()

    /// Border width tokens
    public static let borderWidth: LemonadeBorderWidth = LemonadeBorderWidthTokens()
}

/// Environment key for theme customization
public struct LemonadeThemeKey: EnvironmentKey {
    public static let defaultValue: LemonadeSemanticColors = LemonadeLightTheme()
}

public extension EnvironmentValues {
    var lemonadeTheme: LemonadeSemanticColors {
        get { self[LemonadeThemeKey.self] }
        set { self[LemonadeThemeKey.self] = newValue }
    }
}

/// View extension for convenient theme access
public extension View {
    /// Applies the Lemonade theme to the view hierarchy
    func lemonadeTheme(_ theme: LemonadeSemanticColors = LemonadeLightTheme()) -> some View {
        environment(\.lemonadeTheme, theme)
    }
}
