include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    deprecated_member_use_from_same_package: ignore
    invalid_export_of_internal_element: ignore
    lines_longer_than_80_chars: ignore

formatter:
  trailing_commas: preserve
