package com.teya.lemonade.core

/**
 * Auto-generated enum class containing all icons converted from SVG files.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the svg-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add new icons:
 * 1. Add your SVG file to the svg/pack-dir/ directory
 * 2. Run: kotlin svg-converter.main.kts
 * 
 * @generated by svg-converter.main.kts
 */
public enum class LemonadeCountryFlags: LemonadeAsset {
    ACAscensionIsland,
    ADAndorra,
    AEUnitedArabEmirates,
    AFAfghanistan,
    AGAntiguaAndBarbuda,
    AIAnguilla,
    ALAlbania,
    AMArmenia,
    AOAngola,
    AQAntarctica,
    ARArgentina,
    ASAmericanSamoa,
    ATAustria,
    AUAustralia,
    AWAruba,
    AXAlandIslands,
    AZAzerbaijan,
    BABosniaAndHerzegovina,
    BBBarbados,
    BDBangladesh,
    BEBelgium,
    BFBurkinaFaso,
    BGBulgaria,
    BHBahrain,
    BIBurundi,
    BJBenin,
    BLSaintBarthelemy,
    BMBermuda,
    BNBrunei,
    BOBolivia,
    BQBOBonaire,
    BQSASaba,
    BQSESintEustatius,
    BQCaribbeanNetherlands,
    BRBrazil,
    BSBahamas,
    BTBhutan,
    BVBouvetIsland,
    BWBotswana,
    BYBelarus,
    BZBelize,
    CACanada,
    CCCocosIslands,
    CDCongoDemocraticRepublic,
    CDDemocraticRepublicOfCongo,
    CFCentralAfricanRepublic,
    CGCongo,
    CHSwitzerland,
    CICoteDivoire,
    CKCookIslands,
    CLChile,
    CMCameroon,
    CNChina,
    COColombia,
    CRCostaRica,
    CUCuba,
    CVCaboVerde,
    CWCuracao,
    CXChristmasIsland,
    CYCyprus,
    CZCzechia,
    DEGermany,
    DJDjibouti,
    DKDenmark,
    DMDominica,
    DODominicanRepublic,
    DZAlgeria,
    ECEcuador,
    EEEstonia,
    EGEgypt,
    EHWesternSahara,
    EREritrea,
    ESCTCatalonia,
    ESSpain,
    ETEthiopia,
    EUEuropeanUnion,
    FIFinland,
    FJFiji,
    FKFalklandIslands,
    FMMicronesia,
    FOFaroeIslands,
    FRFrance,
    GAGabon,
    GBENGEngland,
    GBNIRNorthernIreland,
    GBSCTScotland,
    GBWLSWales,
    GBUnitedKingdom,
    GDGrenada,
    GEABAbkhazia,
    GEOSSouthOssetia,
    GEGeorgia,
    GFFrenchGuiana,
    GGGuernsey,
    GHGhana,
    GIGibraltar,
    GLGreenland,
    GMGambia,
    GNGuinea,
    GPGuadeloupe,
    GQEquatorialGuinea,
    GRGreece,
    GSSouthGeorgiaAndSouthSandwichIslands,
    GTGuatemala,
    GUGuam,
    GWGuineaBissau,
    GYGuyana,
    HKHongKong,
    HMHeardIslandAndMcdonaldIslands,
    HNHonduras,
    HRCroatia,
    HTHaiti,
    HUHungary,
    ICCanaryIslands,
    IDIndonesia,
    IEIreland,
    ILIsrael,
    IMIsleOfMan,
    INIndia,
    IOBritishIndianOceanTerritory,
    IQIraq,
    IRIran,
    ISIceland,
    ITItaly,
    JEJersey,
    JMJamaica,
    JOJordan,
    JPJapan,
    KEKenya,
    KGKyrgyzstan,
    KHCambodia,
    KIKiribati,
    KMComoros,
    KNSaintKittsAndNevis,
    KPNorthKorea,
    KRSouthKorea,
    KWKuwait,
    KYCaymanIslands,
    KZKazakhstan,
    LALaos,
    LBLebanon,
    LCSaintLucia,
    LILiechtenstein,
    LKSriLanka,
    LRLiberia,
    LSLesotho,
    LTLithuania,
    LULuxembourg,
    LVLatvia,
    LYLibya,
    MAMorocco,
    MCMonaco,
    MDMoldova,
    MEMontenegro,
    MFSaintMartin,
    MGMadagascar,
    MHMarshallIslands,
    MKNorthMacedonia,
    MLMali,
    MMMyanmar,
    MNMongolia,
    MOMacau,
    MPNorthernMarianaIslands,
    MQMartinique,
    MRMauritania,
    MSMontserrat,
    MTMalta,
    MUMauritius,
    MVMaldives,
    MWMalawi,
    MXMexico,
    MYMalaysia,
    MZMozambique,
    NANamibia,
    NCNewCaledonia,
    NENiger,
    NFNorfolkIsland,
    NGNigeria,
    NINicaragua,
    NLNetherlands,
    NONorway,
    NPNepal,
    NRNauru,
    NUNiue,
    NZNewZealand,
    OMOman,
    PAPanama,
    PEPeru,
    PFFrenchPolynesia,
    PGPapuaNewGuinea,
    PHPhilippines,
    PKPakistan,
    PLPoland,
    PMSaintPierreAndMiquelon,
    PNPitcairnIslands,
    PRPuertoRico,
    PSPalestine,
    PTPortugal,
    PWPalau,
    PYParaguay,
    QAQatar,
    REReunion,
    RORomania,
    RSSerbia,
    RURussia,
    RWRwanda,
    SASaudiArabia,
    SBSolomonIslands,
    SCSeychelles,
    SDSudan,
    SESweden,
    SGSingapore,
    SHSaintHelenaAscensionTristanDaCunha,
    SISlovenia,
    SJSvalbardAndJanMayen,
    SKSlovakia,
    SLSierraLeone,
    SMSanMarino,
    SNSenegal,
    SOSomalia,
    SRSuriname,
    SSSouthSudan,
    STSaoTomeAndPrincipe,
    SVElSalvador,
    SXSintMaarten,
    SYSyria,
    SZEswatini,
    TATristanDaCunha,
    TCTurksAndCaicosIslands,
    TDChad,
    TFFrenchSouthernTerritories,
    TGTogo,
    THThailand,
    TJTajikistan,
    TKTokelau,
    TLTimorLeste,
    TMTurkmenistan,
    TNTunisia,
    TOTonga,
    TRTurkey,
    TTTrinidadAndTobago,
    TVTuvalu,
    TWTaiwan,
    TZTanzania,
    UAUkraine,
    UGUganda,
    UMUnitedStatesOutlyingIslands,
    USUnitedStates,
    UYUruguay,
    UZUzbekistan,
    VAHolySee,
    VCSaintVincentAndTheGrenadines,
    VEVenezuela,
    VGBritishVirginIslands,
    VIUsVirginIslands,
    VNVietnam,
    VUVanuatu,
    WFWallisAndFutuna,
    WSSamoa,
    XKKosovo,
    YEYemen,
    YTMayotte,
    ZASouthAfrica,
    ZMZambia,
    ZWZimbabwe;

    public companion object {
        public fun getOrNull(alpha2: String): LemonadeCountryFlags? =
            when (alpha2.uppercase()) {
                "AC" -> ACAscensionIsland
                "AD" -> ADAndorra
                "AE" -> AEUnitedArabEmirates
                "AF" -> AFAfghanistan
                "AG" -> AGAntiguaAndBarbuda
                "AI" -> AIAnguilla
                "AL" -> ALAlbania
                "AM" -> AMArmenia
                "AO" -> AOAngola
                "AQ" -> AQAntarctica
                "AR" -> ARArgentina
                "AS" -> ASAmericanSamoa
                "AT" -> ATAustria
                "AU" -> AUAustralia
                "AW" -> AWAruba
                "AX" -> AXAlandIslands
                "AZ" -> AZAzerbaijan
                "BA" -> BABosniaAndHerzegovina
                "BB" -> BBBarbados
                "BD" -> BDBangladesh
                "BE" -> BEBelgium
                "BF" -> BFBurkinaFaso
                "BG" -> BGBulgaria
                "BH" -> BHBahrain
                "BI" -> BIBurundi
                "BJ" -> BJBenin
                "BL" -> BLSaintBarthelemy
                "BM" -> BMBermuda
                "BN" -> BNBrunei
                "BO" -> BOBolivia
                "BQ" -> BQCaribbeanNetherlands
                "BR" -> BRBrazil
                "BS" -> BSBahamas
                "BT" -> BTBhutan
                "BV" -> BVBouvetIsland
                "BW" -> BWBotswana
                "BY" -> BYBelarus
                "BZ" -> BZBelize
                "CA" -> CACanada
                "CC" -> CCCocosIslands
                "CD" -> CDCongoDemocraticRepublic
                "CF" -> CFCentralAfricanRepublic
                "CG" -> CGCongo
                "CH" -> CHSwitzerland
                "CI" -> CICoteDivoire
                "CK" -> CKCookIslands
                "CL" -> CLChile
                "CM" -> CMCameroon
                "CN" -> CNChina
                "CO" -> COColombia
                "CR" -> CRCostaRica
                "CU" -> CUCuba
                "CV" -> CVCaboVerde
                "CW" -> CWCuracao
                "CX" -> CXChristmasIsland
                "CY" -> CYCyprus
                "CZ" -> CZCzechia
                "DE" -> DEGermany
                "DJ" -> DJDjibouti
                "DK" -> DKDenmark
                "DM" -> DMDominica
                "DO" -> DODominicanRepublic
                "DZ" -> DZAlgeria
                "EC" -> ECEcuador
                "EE" -> EEEstonia
                "EG" -> EGEgypt
                "EH" -> EHWesternSahara
                "ER" -> EREritrea
                "ES" -> ESSpain
                "ET" -> ETEthiopia
                "EU" -> EUEuropeanUnion
                "FI" -> FIFinland
                "FJ" -> FJFiji
                "FK" -> FKFalklandIslands
                "FM" -> FMMicronesia
                "FO" -> FOFaroeIslands
                "FR" -> FRFrance
                "GA" -> GAGabon
                "GB" -> GBUnitedKingdom
                "GD" -> GDGrenada
                "GE" -> GEGeorgia
                "GF" -> GFFrenchGuiana
                "GG" -> GGGuernsey
                "GH" -> GHGhana
                "GI" -> GIGibraltar
                "GL" -> GLGreenland
                "GM" -> GMGambia
                "GN" -> GNGuinea
                "GP" -> GPGuadeloupe
                "GQ" -> GQEquatorialGuinea
                "GR" -> GRGreece
                "GS" -> GSSouthGeorgiaAndSouthSandwichIslands
                "GT" -> GTGuatemala
                "GU" -> GUGuam
                "GW" -> GWGuineaBissau
                "GY" -> GYGuyana
                "HK" -> HKHongKong
                "HM" -> HMHeardIslandAndMcdonaldIslands
                "HN" -> HNHonduras
                "HR" -> HRCroatia
                "HT" -> HTHaiti
                "HU" -> HUHungary
                "IC" -> ICCanaryIslands
                "ID" -> IDIndonesia
                "IE" -> IEIreland
                "IL" -> ILIsrael
                "IM" -> IMIsleOfMan
                "IN" -> INIndia
                "IO" -> IOBritishIndianOceanTerritory
                "IQ" -> IQIraq
                "IR" -> IRIran
                "IS" -> ISIceland
                "IT" -> ITItaly
                "JE" -> JEJersey
                "JM" -> JMJamaica
                "JO" -> JOJordan
                "JP" -> JPJapan
                "KE" -> KEKenya
                "KG" -> KGKyrgyzstan
                "KH" -> KHCambodia
                "KI" -> KIKiribati
                "KM" -> KMComoros
                "KN" -> KNSaintKittsAndNevis
                "KP" -> KPNorthKorea
                "KR" -> KRSouthKorea
                "KW" -> KWKuwait
                "KY" -> KYCaymanIslands
                "KZ" -> KZKazakhstan
                "LA" -> LALaos
                "LB" -> LBLebanon
                "LC" -> LCSaintLucia
                "LI" -> LILiechtenstein
                "LK" -> LKSriLanka
                "LR" -> LRLiberia
                "LS" -> LSLesotho
                "LT" -> LTLithuania
                "LU" -> LULuxembourg
                "LV" -> LVLatvia
                "LY" -> LYLibya
                "MA" -> MAMorocco
                "MC" -> MCMonaco
                "MD" -> MDMoldova
                "ME" -> MEMontenegro
                "MF" -> MFSaintMartin
                "MG" -> MGMadagascar
                "MH" -> MHMarshallIslands
                "MK" -> MKNorthMacedonia
                "ML" -> MLMali
                "MM" -> MMMyanmar
                "MN" -> MNMongolia
                "MO" -> MOMacau
                "MP" -> MPNorthernMarianaIslands
                "MQ" -> MQMartinique
                "MR" -> MRMauritania
                "MS" -> MSMontserrat
                "MT" -> MTMalta
                "MU" -> MUMauritius
                "MV" -> MVMaldives
                "MW" -> MWMalawi
                "MX" -> MXMexico
                "MY" -> MYMalaysia
                "MZ" -> MZMozambique
                "NA" -> NANamibia
                "NC" -> NCNewCaledonia
                "NE" -> NENiger
                "NF" -> NFNorfolkIsland
                "NG" -> NGNigeria
                "NI" -> NINicaragua
                "NL" -> NLNetherlands
                "NO" -> NONorway
                "NP" -> NPNepal
                "NR" -> NRNauru
                "NU" -> NUNiue
                "NZ" -> NZNewZealand
                "OM" -> OMOman
                "PA" -> PAPanama
                "PE" -> PEPeru
                "PF" -> PFFrenchPolynesia
                "PG" -> PGPapuaNewGuinea
                "PH" -> PHPhilippines
                "PK" -> PKPakistan
                "PL" -> PLPoland
                "PM" -> PMSaintPierreAndMiquelon
                "PN" -> PNPitcairnIslands
                "PR" -> PRPuertoRico
                "PS" -> PSPalestine
                "PT" -> PTPortugal
                "PW" -> PWPalau
                "PY" -> PYParaguay
                "QA" -> QAQatar
                "RE" -> REReunion
                "RO" -> RORomania
                "RS" -> RSSerbia
                "RU" -> RURussia
                "RW" -> RWRwanda
                "SA" -> SASaudiArabia
                "SB" -> SBSolomonIslands
                "SC" -> SCSeychelles
                "SD" -> SDSudan
                "SE" -> SESweden
                "SG" -> SGSingapore
                "SH" -> SHSaintHelenaAscensionTristanDaCunha
                "SI" -> SISlovenia
                "SJ" -> SJSvalbardAndJanMayen
                "SK" -> SKSlovakia
                "SL" -> SLSierraLeone
                "SM" -> SMSanMarino
                "SN" -> SNSenegal
                "SO" -> SOSomalia
                "SR" -> SRSuriname
                "SS" -> SSSouthSudan
                "ST" -> STSaoTomeAndPrincipe
                "SV" -> SVElSalvador
                "SX" -> SXSintMaarten
                "SY" -> SYSyria
                "SZ" -> SZEswatini
                "TA" -> TATristanDaCunha
                "TC" -> TCTurksAndCaicosIslands
                "TD" -> TDChad
                "TF" -> TFFrenchSouthernTerritories
                "TG" -> TGTogo
                "TH" -> THThailand
                "TJ" -> TJTajikistan
                "TK" -> TKTokelau
                "TL" -> TLTimorLeste
                "TM" -> TMTurkmenistan
                "TN" -> TNTunisia
                "TO" -> TOTonga
                "TR" -> TRTurkey
                "TT" -> TTTrinidadAndTobago
                "TV" -> TVTuvalu
                "TW" -> TWTaiwan
                "TZ" -> TZTanzania
                "UA" -> UAUkraine
                "UG" -> UGUganda
                "UM" -> UMUnitedStatesOutlyingIslands
                "US" -> USUnitedStates
                "UY" -> UYUruguay
                "UZ" -> UZUzbekistan
                "VA" -> VAHolySee
                "VC" -> VCSaintVincentAndTheGrenadines
                "VE" -> VEVenezuela
                "VG" -> VGBritishVirginIslands
                "VI" -> VIUsVirginIslands
                "VN" -> VNVietnam
                "VU" -> VUVanuatu
                "WF" -> WFWallisAndFutuna
                "WS" -> WSSamoa
                "XK" -> XKKosovo
                "YE" -> YEYemen
                "YT" -> YTMayotte
                "ZA" -> ZASouthAfrica
                "ZM" -> ZMZambia
                "ZW" -> ZWZimbabwe
                else -> null
            }
    }

}
