package com.teya.lemonade.core

/**
 * Lemonade Design System Radius tokens.
 * Sets a small, clear set of predefined radius values for UI elements to ensure
 *  consistent, scalable rounding across the product.
 * 
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-radius-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-radius-token-converter.main.kts
 * 
 * @generated by scripts/kmp-radius-token-converter.main.kts
 */
public enum class LemonadeRadius {
    Radius0,
    Radius50,
    Radius100,
    Radius150,
    Radius200,
    Radius300,
    Radius400,
    Radius500,
    Radius600,
    Radius800,
    RadiusFull,
}
