package com.teya.lemonade.core

/**
 * Core definition of the LemonadeFontSizes tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public enum class LemonadeFontSizes(public val value: Float) {
    FontSize250(10f),
    FontSize300(12f),
    FontSize350(14f),
    FontSize400(16f),
    FontSize450(18f),
    FontSize500(20f),
    FontSize600(24f),
    FontSize700(28f),
    FontSize800(32f),
    FontSize900(36f),
    FontSize1000(40f),
    FontSize1200(48f),
    FontSize1400(56f),
    FontSize1600(64f),
    FontSize1800(72f),
}
