package com.teya.lemonade.core

/**
 * Core definition of the LemonadeLineHeights tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public enum class LemonadeLineHeights {
    LineHeight250,
    LineHeight300,
    LineHeight350,
    LineHeight400,
    LineHeight450,
    LineHeight500,
    LineHeight600,
    LineHeight650,
    LineHeight700,
    LineHeight800,
    LineHeight900,
    LineHeight1000,
    LineHeight1100,
    LineHeight1200,
    LineHeight1400,
    LineHeight1600,
    LineHeight1800,
    LineHeight2000,
}
