package com.teya.lemonade.core

/**
 * Core definition of the LemonadeFontSizes tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public enum class LemonadeFontSizes {
    FontSize250,
    FontSize300,
    FontSize350,
    FontSize400,
    FontSize450,
    FontSize500,
    FontSize600,
    FontSize700,
    FontSize800,
    FontSize900,
    FontSize1000,
    FontSize1200,
    FontSize1400,
    FontSize1600,
    FontSize1800,
}
