package com.teya.lemonade.core

/**
 * Core definition of the LemonadeLineHeights tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public enum class LemonadeLineHeights(public val value: Float) {
    LineHeight250(10f),
    LineHeight300(12f),
    LineHeight350(14f),
    LineHeight400(16f),
    LineHeight450(18f),
    LineHeight500(20f),
    LineHeight600(24f),
    LineHeight650(26f),
    LineHeight700(28f),
    LineHeight800(32f),
    LineHeight900(36f),
    LineHeight1000(40f),
    LineHeight1100(44f),
    LineHeight1200(48f),
    LineHeight1400(56f),
    LineHeight1600(64f),
    LineHeight1800(72f),
    LineHeight2000(80f),
}
