package com.teya.lemonade.core

/**
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-shadow-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-shadow-token-converter.main.kts
 * 
 * @generated by scripts/kmp-shadow-token-converter.main.kts
 */
public enum class LemonadeShadow {
    Large,
    Medium,
    Small,
    Xsmall,
    None,
}
