package com.teya.lemonade.core

/**
 * Auto-generated enum class containing all icons converted from SVG files.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the svg-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add new icons:
 * 1. Add your SVG file to the svg/pack-dir/ directory
 * 2. Run: kotlin svg-converter.main.kts
 *
 * @generated by svg-converter.main.kts
 */
public enum class LemonadeBrandLogos : LemonadeAsset {
    Amazon,
    Amex,
    ApplePay,
    Dinners,
    Discover,
    Edenred,
    GenericMealOrHealthIssuer,
    GooglePay,
    Jcb,
    Mastercard,
    Multibanco,
    PagoBancomat,
    Pluxee,
    Sepa,
    Sodexo,
    Unionpay,
    Visa,
}
