package com.teya.lemonade.core

/**
 * Core definition of the LemonadeSizes tokens.
 * 
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-dimension-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-dimension-token-converter.main.kts
 * 
 * @generated by scripts/kmp-dimension-token-converter.main.kts
 */
public enum class LemonadeSizes {
    Size0,
    Size50,
    Size100,
    Size150,
    Size200,
    Size250,
    Size300,
    Size350,
    Size400,
    Size450,
    Size500,
    Size550,
    Size600,
    Size700,
    Size750,
    Size800,
    Size900,
    Size1000,
    Size1100,
    Size1200,
    Size1400,
    Size1600,
}
