package com.teya.lemonade.core

/**
 * Core definition of the LemonadeSpaces tokens.
 * 
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-spacing-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-spacing-token-converter.main.kts
 * 
 * @generated by scripts/kmp-spacing-token-converter.main.kts
 */
public enum class LemonadeSpaces {
    Spacing0,
    Spacing50,
    Spacing100,
    Spacing200,
    Spacing300,
    Spacing400,
    Spacing500,
    Spacing600,
    Spacing800,
    Spacing1000,
    Spacing1200,
    Spacing1400,
    Spacing1600,
    Spacing1800,
    Spacing2000,
}
