package com.teya.lemonade

import androidx.compose.runtime.Stable
import androidx.compose.ui.text.font.FontWeight
import com.teya.lemonade.core.LemonadeFontWeights

/**
 * Lemonade Design System Font Weight tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public val LemonadeFontWeights.fontWeight: FontWeight
    get() = when (this) {
        LemonadeFontWeights.Bold -> FontWeight.Bold
        LemonadeFontWeights.Semibold -> FontWeight.SemiBold
        LemonadeFontWeights.Medium -> FontWeight.Medium
        LemonadeFontWeights.Regular -> FontWeight.Normal
    }

public interface LemonadeFontWeightValues {
    public val bold: FontWeight
    public val semibold: FontWeight
    public val medium: FontWeight
    public val regular: FontWeight
}

@Stable
internal data class InternalLemonadeFontWeightValues(
    override val bold: FontWeight = LemonadeFontWeights.Bold.fontWeight,
    override val semibold: FontWeight = LemonadeFontWeights.Semibold.fontWeight,
    override val medium: FontWeight = LemonadeFontWeights.Medium.fontWeight,
    override val regular: FontWeight = LemonadeFontWeights.Regular.fontWeight,
): LemonadeFontWeightValues
