package com.teya.lemonade

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.teya.lemonade.core.LemonadeSpaces
import androidx.compose.runtime.Stable

/**
 * Lemonade Design System Space tokens.
 * Provides a consistent and scalable way to manage spacing across interfaces.
 * These values can be used for margins, paddings, and gaps to create balanced layouts.
 * 
 * 
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-spacing-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-spacing-token-converter.main.kts
 * 
 * @generated by scripts/kmp-spacing-token-converter.main.kts
 */
public val LemonadeSpaces.dp: Dp
    get() {
        return when (this) {
            LemonadeSpaces.Spacing0 -> 0.dp
            LemonadeSpaces.Spacing50 -> 2.dp
            LemonadeSpaces.Spacing100 -> 4.dp
            LemonadeSpaces.Spacing200 -> 8.dp
            LemonadeSpaces.Spacing300 -> 12.dp
            LemonadeSpaces.Spacing400 -> 16.dp
            LemonadeSpaces.Spacing500 -> 20.dp
            LemonadeSpaces.Spacing600 -> 24.dp
            LemonadeSpaces.Spacing800 -> 32.dp
            LemonadeSpaces.Spacing1000 -> 40.dp
            LemonadeSpaces.Spacing1200 -> 48.dp
            LemonadeSpaces.Spacing1400 -> 56.dp
            LemonadeSpaces.Spacing1600 -> 64.dp
            LemonadeSpaces.Spacing1800 -> 72.dp
            LemonadeSpaces.Spacing2000 -> 80.dp
        }
    }

public interface LemonadeSpaceValues {
    public val spacing0: Dp
    public val spacing50: Dp
    public val spacing100: Dp
    public val spacing200: Dp
    public val spacing300: Dp
    public val spacing400: Dp
    public val spacing500: Dp
    public val spacing600: Dp
    public val spacing800: Dp
    public val spacing1000: Dp
    public val spacing1200: Dp
    public val spacing1400: Dp
    public val spacing1600: Dp
    public val spacing1800: Dp
    public val spacing2000: Dp
}

@Stable
internal data class InternalLemonadeSpaceValues(
    override val spacing0: Dp = LemonadeSpaces.Spacing0.dp,
    override val spacing50: Dp = LemonadeSpaces.Spacing50.dp,
    override val spacing100: Dp = LemonadeSpaces.Spacing100.dp,
    override val spacing200: Dp = LemonadeSpaces.Spacing200.dp,
    override val spacing300: Dp = LemonadeSpaces.Spacing300.dp,
    override val spacing400: Dp = LemonadeSpaces.Spacing400.dp,
    override val spacing500: Dp = LemonadeSpaces.Spacing500.dp,
    override val spacing600: Dp = LemonadeSpaces.Spacing600.dp,
    override val spacing800: Dp = LemonadeSpaces.Spacing800.dp,
    override val spacing1000: Dp = LemonadeSpaces.Spacing1000.dp,
    override val spacing1200: Dp = LemonadeSpaces.Spacing1200.dp,
    override val spacing1400: Dp = LemonadeSpaces.Spacing1400.dp,
    override val spacing1600: Dp = LemonadeSpaces.Spacing1600.dp,
    override val spacing1800: Dp = LemonadeSpaces.Spacing1800.dp,
    override val spacing2000: Dp = LemonadeSpaces.Spacing2000.dp,
): LemonadeSpaceValues
