package com.teya.lemonade

import androidx.compose.ui.graphics.Color

/**
 * Semantic color tokens from Lemonade DS - Foundations
 * Organized by usage categories: Background, Content, Border, and Interaction
 * These tokens map to primitive colors and provide semantic meaning for UI elements
 * See [Lemonade  semantic colors](https://www.figma.com/design/3DI1AqqkYgRJgYCjOXjbDO/Review-and-update-colors?node-id=97-4923)
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-theme-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-theme-token-converter.main.kts
 *
 * @generated by scripts/kmp-theme-token-converter.main.kts
 */
public interface LemonadeSemanticColors {
    public val interaction: InteractionColors
    public val border: BorderColors
    public val content: ContentColors
    public val background: BackgroundColors

    public interface InteractionColors {
        public val bgNeutralSubtleInteractive: Color
        public val bgPositiveSubtleInteractive: Color
        public val bgInfoSubtleInteractive: Color
        public val bgNeutralInteractive: Color
        public val bgBrandHighInteractive: Color
        public val bgDefaultInteractive: Color
        public val bgCautionInteractive: Color
        public val bgPositiveInteractive: Color
        public val bgSubtleInteractive: Color
        public val bgInfoInteractive: Color
        public val bgCautionSubtleInteractive: Color
        public val bgCriticalInteractive: Color
        public val bgBrandInteractive: Color
        public val bgElevatedInteractive: Color
        public val bgCriticalSubtleInteractive: Color
        public val bgDefaultPressed: Color
        public val bgSubtlePressed: Color
        public val bgElevatedPressed: Color
        public val bgBrandPressed: Color
        public val bgBrandHighPressed: Color
        public val bgCriticalPressed: Color
        public val bgCautionPressed: Color
        public val bgInfoPressed: Color
        public val bgPositivePressed: Color
        public val bgNeutralPressed: Color
        public val bgCriticalSubtlePressed: Color
        public val bgCautionSubtlePressed: Color
        public val bgInfoSubtlePressed: Color
        public val bgPositiveSubtlePressed: Color
        public val bgNeutralSubtlePressed: Color
        public val bgElevatedHighInteractive: Color
        public val bgBrandElevatedInteractive: Color
        public val bgBrandElevatedPressed: Color
    }

    public interface BorderColors {
        public val borderBrandInverse: Color
        public val borderSelectedInverse: Color
        public val borderNeutralMediumInverse: Color
        public val borderNeutralLowInverse: Color
        public val borderAlwaysDark: Color
        public val borderPositiveSubtle: Color
        public val borderInfoSubtle: Color
        public val borderCautionSubtle: Color
        public val borderCriticalSubtle: Color
        public val borderPositive: Color
        public val borderInfo: Color
        public val borderCaution: Color
        public val borderOnBrandMedium: Color
        public val borderBrand: Color
        public val borderSelected: Color
        public val borderOnBrandLow: Color
        public val borderOnBrandHigh: Color
        public val borderCritical: Color
        public val borderNeutralLow: Color
        public val borderNeutralMedium: Color
        public val borderAlwaysLight: Color
        public val borderNeutralHigh: Color
        public val borderNeutralHighInverse: Color
        public val borderAlwaysLightLow: Color
        public val borderAlwaysLightMedium: Color
        public val borderAlwaysLightHigh: Color
        public val borderAlwaysDarkLow: Color
        public val borderAlwaysDarkMedium: Color
        public val borderAlwaysDarkHigh: Color
    }

    public interface ContentColors {
        public val contentOnBrandLow: Color
        public val contentBrand: Color
        public val contentCaution: Color
        public val contentInfo: Color
        public val contentTertiary: Color
        public val contentAlwaysLight: Color
        public val contentSecondary: Color
        public val contentPrimaryInverse: Color
        public val contentPositive: Color
        public val contentTertiaryInverse: Color
        public val contentAlwaysDark: Color
        public val contentNeutral: Color
        public val contentBrandInverse: Color
        public val contentSecondaryInverse: Color
        public val contentCritical: Color
        public val contentOnBrandHigh: Color
        public val contentPrimary: Color
        public val contentCriticalOnColor: Color
        public val contentCautionOnColor: Color
        public val contentInfoOnColor: Color
        public val contentPositiveOnColor: Color
        public val contentNeutralOnColor: Color
        public val contentBrandHigh: Color
    }

    public interface BackgroundColors {
        public val bgAlwaysLight: Color
        public val bgAlwaysDark: Color
        public val bgDefaultInverse: Color
        public val bgNeutralSubtle: Color
        public val bgCautionSubtle: Color
        public val bgCriticalSubtle: Color
        public val bgNeutral: Color
        public val bgBrandSubtle: Color
        public val bgSubtleInverse: Color
        public val bgBrandElevated: Color
        public val bgPositiveSubtle: Color
        public val bgDefault: Color
        public val bgCritical: Color
        public val bgBrandHigh: Color
        public val bgCaution: Color
        public val bgBrand: Color
        public val bgElevated: Color
        public val bgElevatedInverse: Color
        public val bgSubtle: Color
        public val bgInfo: Color
        public val bgPositive: Color
        public val bgInfoSubtle: Color
        public val bgElevatedHigh: Color
    }
}
