package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Lemonade Design System Opacity tokens.
 * Provides a consistent and scalable way to manage opacity across interfaces.
 * These values can be used for disabled components and general transparency handling.
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-opacity-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-opacity-token-converter.main.kts
 * 
 * @generated by scripts/kmp-opacity-token-converter.main.kts
 */
public interface LemonadeOpacity {
    public val base: Base
    public val state: State
    public interface Base {
        public val opacity0: Float
        public val opacity5: Float
        public val opacity10: Float
        public val opacity20: Float
        public val opacity30: Float
        public val opacity40: Float
        public val opacity50: Float
        public val opacity60: Float
        public val opacity70: Float
        public val opacity80: Float
        public val opacity90: Float
        public val opacity100: Float
    }
    public interface State {
        public val opacityPressed: Float
        public val opacityDisabled: Float
    }
}

@Stable
internal class InternalLemonadeOpacityTokens: LemonadeOpacity {
    override val base: LemonadeOpacity.Base = object: LemonadeOpacity.Base {
        override val opacity0: Float = 0.0f
        override val opacity5: Float = 0.05f
        override val opacity10: Float = 0.1f
        override val opacity20: Float = 0.2f
        override val opacity30: Float = 0.3f
        override val opacity40: Float = 0.4f
        override val opacity50: Float = 0.5f
        override val opacity60: Float = 0.6f
        override val opacity70: Float = 0.7f
        override val opacity80: Float = 0.8f
        override val opacity90: Float = 0.9f
        override val opacity100: Float = 1.0f
    }
    override val state: LemonadeOpacity.State = object: LemonadeOpacity.State {
        override val opacityPressed: Float = 0.2f
        override val opacityDisabled: Float = 0.4f
    }
}
