package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Light theme implementation of semantic colors
 * See [LemonadeSemanticColors] for details on the color structure.
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-theme-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-theme-token-converter.main.kts
 * 
 * @generated by scripts/kmp-theme-token-converter.main.kts
 */
@Stable
@OptIn(InternalLemonadeApi::class)
internal object LemonadeLightTheme : LemonadeSemanticColors {
    override val interaction = object : LemonadeSemanticColors.InteractionColors {
        override val bgNeutralSubtleInteractive = LemonadePrimitiveColors.Solid.Black.black200
        override val bgPositiveSubtleInteractive = LemonadePrimitiveColors.Alpha.GreenLime.alpha200
        override val bgInfoSubtleInteractive = LemonadePrimitiveColors.Alpha.Blue.alpha200
        override val bgNeutralInteractive = LemonadePrimitiveColors.Solid.Neutral.neutral700
        override val bgBrandHighInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
        override val bgDefaultInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha50
        override val bgCautionInteractive = LemonadePrimitiveColors.Solid.Orange.orange600
        override val bgPositiveInteractive = LemonadePrimitiveColors.Solid.GreenLime.greenLime600
        override val bgSubtleInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha100
        override val bgInfoInteractive = LemonadePrimitiveColors.Solid.Blue.blue600
        override val bgCautionSubtleInteractive = LemonadePrimitiveColors.Alpha.Orange.alpha200
        override val bgCriticalInteractive = LemonadePrimitiveColors.Solid.Red.red600
        override val bgBrandInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
        override val bgElevatedInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha200
        override val bgCriticalSubtleInteractive = LemonadePrimitiveColors.Alpha.Red.alpha200
        override val bgDefaultPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha100
        override val bgElevatedPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha300
        override val bgBrandPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
        override val bgBrandHighPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime950
        override val bgCriticalPressed = LemonadePrimitiveColors.Solid.Red.red700
        override val bgCautionPressed = LemonadePrimitiveColors.Solid.Amber.amber700
        override val bgInfoPressed = LemonadePrimitiveColors.Solid.Blue.blue700
        override val bgPositivePressed = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
        override val bgNeutralPressed = LemonadePrimitiveColors.Solid.Neutral.neutral800
        override val bgCautionSubtlePressed = LemonadePrimitiveColors.Alpha.Amber.alpha300
        override val bgInfoSubtlePressed = LemonadePrimitiveColors.Alpha.Blue.alpha300
        override val bgPositiveSubtlePressed = LemonadePrimitiveColors.Alpha.GreenLime.alpha300
        override val bgNeutralSubtlePressed = LemonadePrimitiveColors.Solid.Black.black300
        override val bgElevatedHighInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha300
        override val bgBrandElevatedInteractive = LemonadePrimitiveColors.Solid.White.white500
        override val bgBrandElevatedPressed = LemonadePrimitiveColors.Solid.White.white600
    }
    override val border = object : LemonadeSemanticColors.BorderColors {
        override val borderBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
        override val borderSelectedInverse = LemonadePrimitiveColors.Solid.White.white700
        override val borderNeutralMediumInverse = LemonadePrimitiveColors.Solid.White.white300
        override val borderNeutralLowInverse = LemonadePrimitiveColors.Solid.White.white100
        override val borderAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        override val borderPositiveSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha500
        override val borderInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha500
        override val borderCautionSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha500
        override val borderCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha500
        override val borderPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
        override val borderInfo = LemonadePrimitiveColors.Solid.Blue.blue700
        override val borderCaution = LemonadePrimitiveColors.Solid.Amber.amber700
        override val borderOnBrandMedium = LemonadePrimitiveColors.Solid.White.white500
        override val borderBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
        override val borderSelected = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        override val borderOnBrandLow = LemonadePrimitiveColors.Solid.White.white300
        override val borderOnBrandHigh = LemonadePrimitiveColors.Solid.White.white700
        override val borderCritical = LemonadePrimitiveColors.Solid.Red.red700
        override val borderNeutralLow = LemonadePrimitiveColors.Alpha.Neutral.alpha100
        override val borderNeutralMedium = LemonadePrimitiveColors.Alpha.Neutral.alpha200
        override val borderAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
        override val borderNeutralHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha300
        override val borderNeutralHighInverse = LemonadePrimitiveColors.Solid.White.white400
    }
    override val content = object : LemonadeSemanticColors.ContentColors {
        override val contentOnBrandLow = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
        override val contentBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime700
        override val contentCaution = LemonadePrimitiveColors.Solid.Amber.amber700
        override val contentInfo = LemonadePrimitiveColors.Solid.Blue.blue800
        override val contentTertiary = LemonadePrimitiveColors.Alpha.Neutral.alpha400
        override val contentAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
        override val contentSecondary = LemonadePrimitiveColors.Alpha.Neutral.alpha600
        override val contentPrimaryInverse = LemonadePrimitiveColors.Solid.White.white950
        override val contentPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime700
        override val contentTertiaryInverse = LemonadePrimitiveColors.Solid.White.white700
        override val contentAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha950
        override val contentNeutral = LemonadePrimitiveColors.Solid.Neutral.neutral950
        override val contentBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
        override val contentSecondaryInverse = LemonadePrimitiveColors.Solid.White.white900
        override val contentCritical = LemonadePrimitiveColors.Solid.Red.red600
        override val contentOnBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
        override val contentPrimary = LemonadePrimitiveColors.Alpha.Neutral.alpha900
        override val contentCautionOnColor = LemonadePrimitiveColors.Solid.Amber.amber400
        override val contentInfoOnColor = LemonadePrimitiveColors.Solid.Blue.blue400
        override val contentPositiveOnColor = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
        override val contentNeutralOnColor = LemonadePrimitiveColors.Solid.White.white700
        override val contentBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime800
    }
    override val background = object : LemonadeSemanticColors.BackgroundColors {
        override val bgAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
        override val bgAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha950
        override val bgDefaultInverse = LemonadePrimitiveColors.Solid.Neutral.neutral950
        override val bgNeutralSubtle = LemonadePrimitiveColors.Alpha.Neutral.alpha100
        override val bgCautionSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha100
        override val bgCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha100
        override val bgNeutral = LemonadePrimitiveColors.Solid.Neutral.neutral600
        override val bgBrandSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha200
        override val bgSubtleInverse = LemonadePrimitiveColors.Solid.Neutral.neutral900
        override val bgBrandElevated = LemonadePrimitiveColors.Solid.White.white400
        override val bgPositiveSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha100
        override val bgDefault = LemonadePrimitiveColors.Solid.White.white950
        override val bgCritical = LemonadePrimitiveColors.Solid.Red.red500
        override val bgBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime800
        override val bgCaution = LemonadePrimitiveColors.Solid.Amber.amber600
        override val bgBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
        override val bgElevated = LemonadePrimitiveColors.Alpha.Neutral.alpha100
        override val bgElevatedInverse = LemonadePrimitiveColors.Solid.White.white50
        override val bgSubtle = LemonadePrimitiveColors.Solid.Neutral.neutral50
        override val bgInfo = LemonadePrimitiveColors.Solid.Blue.blue600
        override val bgPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime600
        override val bgInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha100
        override val bgElevatedHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha200
    }
}
