package com.teya.lemonade

import androidx.compose.runtime.Stable

/**
 * Dark theme implementation of semantic colors
 * See [LemonadeSemanticColors] for details on the color structure.
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-theme-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-theme-token-converter.main.kts
 *
 * @generated by scripts/kmp-theme-token-converter.main.kts
 */
@Stable
@OptIn(InternalLemonadeApi::class)
public object LemonadeDarkTheme : LemonadeSemanticColors {
    override val interaction: LemonadeSemanticColors.InteractionColors =
        object : LemonadeSemanticColors.InteractionColors {
            override val bgNeutralSubtleInteractive = LemonadePrimitiveColors.Solid.Black.black200
            override val bgPositiveSubtleInteractive = LemonadePrimitiveColors.Alpha.Green.alpha200
            override val bgInfoSubtleInteractive = LemonadePrimitiveColors.Alpha.Blue.alpha200
            override val bgNeutralInteractive = LemonadePrimitiveColors.Solid.Neutral.neutral700
            override val bgBrandHighInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val bgDefaultInteractive = LemonadePrimitiveColors.Solid.Neutral.neutral50
            override val bgCautionInteractive = LemonadePrimitiveColors.Solid.Orange.orange500
            override val bgPositiveInteractive = LemonadePrimitiveColors.Solid.Green.green500
            override val bgSubtleInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgInfoInteractive = LemonadePrimitiveColors.Solid.Blue.blue500
            override val bgCautionSubtleInteractive = LemonadePrimitiveColors.Alpha.Orange.alpha200
            override val bgCriticalInteractive = LemonadePrimitiveColors.Solid.Red.red500
            override val bgBrandInteractive = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val bgElevatedInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val bgCriticalSubtleInteractive = LemonadePrimitiveColors.Alpha.Red.alpha200
            override val bgDefaultPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgSubtlePressed = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val bgElevatedPressed = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgBrandPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val bgBrandHighPressed = LemonadePrimitiveColors.Solid.YellowLime.yellowLime950
            override val bgCriticalPressed = LemonadePrimitiveColors.Solid.Red.red700
            override val bgCautionPressed = LemonadePrimitiveColors.Solid.Amber.amber700
            override val bgInfoPressed = LemonadePrimitiveColors.Solid.Blue.blue700
            override val bgPositivePressed = LemonadePrimitiveColors.Solid.Green.green600
            override val bgNeutralPressed = LemonadePrimitiveColors.Solid.Neutral.neutral800
            override val bgCriticalSubtlePressed = LemonadePrimitiveColors.Alpha.Red.alpha300
            override val bgCautionSubtlePressed = LemonadePrimitiveColors.Alpha.Amber.alpha300
            override val bgInfoSubtlePressed = LemonadePrimitiveColors.Alpha.Blue.alpha300
            override val bgPositiveSubtlePressed = LemonadePrimitiveColors.Alpha.Green.alpha300
            override val bgNeutralSubtlePressed = LemonadePrimitiveColors.Solid.Black.black300
            override val bgElevatedHighInteractive = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val bgBrandElevatedInteractive = LemonadePrimitiveColors.Solid.White.white500
            override val bgBrandElevatedPressed = LemonadePrimitiveColors.Solid.White.white600
        }
    override val border: LemonadeSemanticColors.BorderColors =
        object : LemonadeSemanticColors.BorderColors {
            override val borderBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val borderSelectedInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val borderNeutralMediumInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val borderNeutralLowInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val borderAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val borderPositiveSubtle = LemonadePrimitiveColors.Alpha.Green.alpha400
            override val borderInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha400
            override val borderCautionSubtle = LemonadePrimitiveColors.Alpha.Orange.alpha400
            override val borderCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha400
            override val borderPositive = LemonadePrimitiveColors.Solid.Green.green400
            override val borderInfo = LemonadePrimitiveColors.Solid.Blue.blue400
            override val borderCaution = LemonadePrimitiveColors.Solid.Amber.amber400
            override val borderOnBrandMedium = LemonadePrimitiveColors.Solid.White.white600
            override val borderBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val borderSelected = LemonadePrimitiveColors.Solid.White.white900
            override val borderOnBrandLow = LemonadePrimitiveColors.Solid.White.white400
            override val borderOnBrandHigh = LemonadePrimitiveColors.Solid.White.white700
            override val borderCritical = LemonadePrimitiveColors.Solid.Red.red400
            override val borderNeutralLow = LemonadePrimitiveColors.Solid.White.white100
            override val borderNeutralMedium = LemonadePrimitiveColors.Solid.White.white200
            override val borderAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val borderNeutralHigh = LemonadePrimitiveColors.Solid.White.white300
            override val borderNeutralHighInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha300
            override val borderAlwaysLightLow = LemonadePrimitiveColors.Solid.White.white100
            override val borderAlwaysLightMedium = LemonadePrimitiveColors.Solid.White.white300
            override val borderAlwaysLightHigh = LemonadePrimitiveColors.Solid.White.white500
            override val borderAlwaysDarkLow = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val borderAlwaysDarkMedium = LemonadePrimitiveColors.Alpha.Neutral.alpha200
            override val borderAlwaysDarkHigh = LemonadePrimitiveColors.Alpha.Neutral.alpha300
        }
    override val content: LemonadeSemanticColors.ContentColors =
        object : LemonadeSemanticColors.ContentColors {
            override val contentOnBrandLow = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val contentBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime600
            override val contentCaution = LemonadePrimitiveColors.Solid.Amber.amber500
            override val contentInfo = LemonadePrimitiveColors.Solid.Blue.blue500
            override val contentTertiary = LemonadePrimitiveColors.Solid.White.white500
            override val contentAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val contentSecondary = LemonadePrimitiveColors.Solid.White.white600
            override val contentPrimaryInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentPositive = LemonadePrimitiveColors.Solid.Green.green500
            override val contentTertiaryInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha500
            override val contentAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha950
            override val contentNeutral = LemonadePrimitiveColors.Solid.White.white900
            override val contentBrandInverse = LemonadePrimitiveColors.Solid.YellowLime.yellowLime800
            override val contentSecondaryInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha600
            override val contentCritical = LemonadePrimitiveColors.Solid.Red.red500
            override val contentOnBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime900
            override val contentPrimary = LemonadePrimitiveColors.Solid.White.white900
            override val contentCriticalOnColor = LemonadePrimitiveColors.Solid.Red.red600
            override val contentCautionOnColor = LemonadePrimitiveColors.Solid.Amber.amber600
            override val contentInfoOnColor = LemonadePrimitiveColors.Solid.Blue.blue700
            override val contentPositiveOnColor = LemonadePrimitiveColors.Solid.Green.green700
            override val contentNeutralOnColor = LemonadePrimitiveColors.Alpha.Neutral.alpha900
            override val contentBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
        }
    override val background: LemonadeSemanticColors.BackgroundColors =
        object : LemonadeSemanticColors.BackgroundColors {
            override val bgAlwaysLight = LemonadePrimitiveColors.Solid.White.white950
            override val bgAlwaysDark = LemonadePrimitiveColors.Alpha.Neutral.alpha950
            override val bgDefaultInverse = LemonadePrimitiveColors.Solid.White.white950
            override val bgNeutralSubtle = LemonadePrimitiveColors.Solid.White.white200
            override val bgCautionSubtle = LemonadePrimitiveColors.Alpha.Amber.alpha300
            override val bgCriticalSubtle = LemonadePrimitiveColors.Alpha.Red.alpha300
            override val bgNeutral = LemonadePrimitiveColors.Solid.Neutral.neutral400
            override val bgBrandSubtle = LemonadePrimitiveColors.Alpha.YellowLime.alpha50
            override val bgSubtleInverse = LemonadePrimitiveColors.Solid.Neutral.neutral200
            override val bgBrandElevated = LemonadePrimitiveColors.Solid.White.white300
            override val bgPositiveSubtle = LemonadePrimitiveColors.Alpha.GreenLime.alpha300
            override val bgDefault = LemonadePrimitiveColors.Solid.Neutral.neutral900
            override val bgCritical = LemonadePrimitiveColors.Solid.Red.red400
            override val bgBrandHigh = LemonadePrimitiveColors.Solid.YellowLime.yellowLime400
            override val bgCaution = LemonadePrimitiveColors.Solid.Amber.amber400
            override val bgBrand = LemonadePrimitiveColors.Solid.YellowLime.yellowLime500
            override val bgElevated = LemonadePrimitiveColors.Solid.White.white50
            override val bgElevatedInverse = LemonadePrimitiveColors.Alpha.Neutral.alpha100
            override val bgSubtle = LemonadePrimitiveColors.Solid.Neutral.neutral950
            override val bgInfo = LemonadePrimitiveColors.Solid.Blue.blue400
            override val bgPositive = LemonadePrimitiveColors.Solid.GreenLime.greenLime400
            override val bgInfoSubtle = LemonadePrimitiveColors.Alpha.Blue.alpha300
            override val bgElevatedHigh = LemonadePrimitiveColors.Solid.White.white100
        }
    override val shadow: LemonadeSemanticColors.ShadowColors =
        object : LemonadeSemanticColors.ShadowColors {
            override val shadowDefault = LemonadePrimitiveColors.Solid.Black.black500
        }
}
