package com.teya.lemonade

import androidx.compose.runtime.Stable
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp
import com.teya.lemonade.core.LemonadeLineHeights

/**
 * Lemonade Design System Line Height tokens.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public val LemonadeLineHeights.sp: TextUnit
    get() = value.sp

public interface LemonadeLineHeightValues {
    public val lineHeight250: TextUnit
    public val lineHeight300: TextUnit
    public val lineHeight350: TextUnit
    public val lineHeight400: TextUnit
    public val lineHeight450: TextUnit
    public val lineHeight500: TextUnit
    public val lineHeight600: TextUnit
    public val lineHeight650: TextUnit
    public val lineHeight700: TextUnit
    public val lineHeight800: TextUnit
    public val lineHeight900: TextUnit
    public val lineHeight1000: TextUnit
    public val lineHeight1100: TextUnit
    public val lineHeight1200: TextUnit
    public val lineHeight1400: TextUnit
    public val lineHeight1600: TextUnit
    public val lineHeight1800: TextUnit
    public val lineHeight2000: TextUnit
}

@Stable
internal data class InternalLemonadeLineHeightValues(
    override val lineHeight250: TextUnit = LemonadeLineHeights.LineHeight250.sp,
    override val lineHeight300: TextUnit = LemonadeLineHeights.LineHeight300.sp,
    override val lineHeight350: TextUnit = LemonadeLineHeights.LineHeight350.sp,
    override val lineHeight400: TextUnit = LemonadeLineHeights.LineHeight400.sp,
    override val lineHeight450: TextUnit = LemonadeLineHeights.LineHeight450.sp,
    override val lineHeight500: TextUnit = LemonadeLineHeights.LineHeight500.sp,
    override val lineHeight600: TextUnit = LemonadeLineHeights.LineHeight600.sp,
    override val lineHeight650: TextUnit = LemonadeLineHeights.LineHeight650.sp,
    override val lineHeight700: TextUnit = LemonadeLineHeights.LineHeight700.sp,
    override val lineHeight800: TextUnit = LemonadeLineHeights.LineHeight800.sp,
    override val lineHeight900: TextUnit = LemonadeLineHeights.LineHeight900.sp,
    override val lineHeight1000: TextUnit = LemonadeLineHeights.LineHeight1000.sp,
    override val lineHeight1100: TextUnit = LemonadeLineHeights.LineHeight1100.sp,
    override val lineHeight1200: TextUnit = LemonadeLineHeights.LineHeight1200.sp,
    override val lineHeight1400: TextUnit = LemonadeLineHeights.LineHeight1400.sp,
    override val lineHeight1600: TextUnit = LemonadeLineHeights.LineHeight1600.sp,
    override val lineHeight1800: TextUnit = LemonadeLineHeights.LineHeight1800.sp,
    override val lineHeight2000: TextUnit = LemonadeLineHeights.LineHeight2000.sp,
) : LemonadeLineHeightValues
