package com.teya.lemonade

import androidx.compose.runtime.Stable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.teya.lemonade.core.LemonadeSizes

/**
 * Lemonade Design System Size tokens.
 * Provides a consistent and scalable way to manage spacing across interfaces.
 * These values can be used for margins, paddings, and gaps to create balanced layouts.
 *
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-dimension-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-dimension-token-converter.main.kts
 *
 * @generated by scripts/kmp-dimension-token-converter.main.kts
 */
public val LemonadeSizes.dp: Dp
    get() {
        return when (this) {
            LemonadeSizes.Size0 -> 0.dp
            LemonadeSizes.Size50 -> 2.dp
            LemonadeSizes.Size100 -> 4.dp
            LemonadeSizes.Size150 -> 6.dp
            LemonadeSizes.Size200 -> 8.dp
            LemonadeSizes.Size250 -> 10.dp
            LemonadeSizes.Size300 -> 12.dp
            LemonadeSizes.Size350 -> 14.dp
            LemonadeSizes.Size400 -> 16.dp
            LemonadeSizes.Size450 -> 18.dp
            LemonadeSizes.Size500 -> 20.dp
            LemonadeSizes.Size550 -> 22.dp
            LemonadeSizes.Size600 -> 24.dp
            LemonadeSizes.Size700 -> 28.dp
            LemonadeSizes.Size750 -> 30.dp
            LemonadeSizes.Size800 -> 32.dp
            LemonadeSizes.Size900 -> 36.dp
            LemonadeSizes.Size1000 -> 40.dp
            LemonadeSizes.Size1100 -> 44.dp
            LemonadeSizes.Size1200 -> 48.dp
            LemonadeSizes.Size1400 -> 56.dp
            LemonadeSizes.Size1600 -> 64.dp
        }
    }

public interface LemonadeSizeValues {
    public val size0: Dp
    public val size50: Dp
    public val size100: Dp
    public val size150: Dp
    public val size200: Dp
    public val size250: Dp
    public val size300: Dp
    public val size350: Dp
    public val size400: Dp
    public val size450: Dp
    public val size500: Dp
    public val size550: Dp
    public val size600: Dp
    public val size700: Dp
    public val size750: Dp
    public val size800: Dp
    public val size900: Dp
    public val size1000: Dp
    public val size1100: Dp
    public val size1200: Dp
    public val size1400: Dp
    public val size1600: Dp
}

@Stable
internal data class InternalLemonadeSizeValues(
    override val size0: Dp = LemonadeSizes.Size0.dp,
    override val size50: Dp = LemonadeSizes.Size50.dp,
    override val size100: Dp = LemonadeSizes.Size100.dp,
    override val size150: Dp = LemonadeSizes.Size150.dp,
    override val size200: Dp = LemonadeSizes.Size200.dp,
    override val size250: Dp = LemonadeSizes.Size250.dp,
    override val size300: Dp = LemonadeSizes.Size300.dp,
    override val size350: Dp = LemonadeSizes.Size350.dp,
    override val size400: Dp = LemonadeSizes.Size400.dp,
    override val size450: Dp = LemonadeSizes.Size450.dp,
    override val size500: Dp = LemonadeSizes.Size500.dp,
    override val size550: Dp = LemonadeSizes.Size550.dp,
    override val size600: Dp = LemonadeSizes.Size600.dp,
    override val size700: Dp = LemonadeSizes.Size700.dp,
    override val size750: Dp = LemonadeSizes.Size750.dp,
    override val size800: Dp = LemonadeSizes.Size800.dp,
    override val size900: Dp = LemonadeSizes.Size900.dp,
    override val size1000: Dp = LemonadeSizes.Size1000.dp,
    override val size1100: Dp = LemonadeSizes.Size1100.dp,
    override val size1200: Dp = LemonadeSizes.Size1200.dp,
    override val size1400: Dp = LemonadeSizes.Size1400.dp,
    override val size1600: Dp = LemonadeSizes.Size1600.dp,
) : LemonadeSizeValues
