package com.teya.lemonade

import androidx.compose.runtime.Stable
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp
import com.teya.lemonade.core.LemonadeFontSizes

/**
 * Lemonade Design System Font Size tokens.
 * Provides font sizes as TextUnit (sp) values.
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-typography-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-typography-token-converter.main.kts
 *
 * @generated by scripts/kmp-typography-token-converter.main.kts
 */
public val LemonadeFontSizes.sp: TextUnit
    get() = when (this) {
        LemonadeFontSizes.FontSize250 -> 10.sp
        LemonadeFontSizes.FontSize300 -> 12.sp
        LemonadeFontSizes.FontSize350 -> 14.sp
        LemonadeFontSizes.FontSize400 -> 16.sp
        LemonadeFontSizes.FontSize450 -> 18.sp
        LemonadeFontSizes.FontSize500 -> 20.sp
        LemonadeFontSizes.FontSize600 -> 24.sp
        LemonadeFontSizes.FontSize700 -> 28.sp
        LemonadeFontSizes.FontSize800 -> 32.sp
        LemonadeFontSizes.FontSize900 -> 36.sp
        LemonadeFontSizes.FontSize1000 -> 40.sp
        LemonadeFontSizes.FontSize1200 -> 48.sp
        LemonadeFontSizes.FontSize1400 -> 56.sp
        LemonadeFontSizes.FontSize1600 -> 64.sp
        LemonadeFontSizes.FontSize1800 -> 72.sp
    }

public const val lemonadeFontFamily: String = "Figtree"

public interface LemonadeFontSizeValues {
    public val fontSize250: TextUnit
    public val fontSize300: TextUnit
    public val fontSize350: TextUnit
    public val fontSize400: TextUnit
    public val fontSize450: TextUnit
    public val fontSize500: TextUnit
    public val fontSize600: TextUnit
    public val fontSize700: TextUnit
    public val fontSize800: TextUnit
    public val fontSize900: TextUnit
    public val fontSize1000: TextUnit
    public val fontSize1200: TextUnit
    public val fontSize1400: TextUnit
    public val fontSize1600: TextUnit
    public val fontSize1800: TextUnit
}

@Stable
internal data class InternalLemonadeFontSizeValues(
    override val fontSize250: TextUnit = LemonadeFontSizes.FontSize250.sp,
    override val fontSize300: TextUnit = LemonadeFontSizes.FontSize300.sp,
    override val fontSize350: TextUnit = LemonadeFontSizes.FontSize350.sp,
    override val fontSize400: TextUnit = LemonadeFontSizes.FontSize400.sp,
    override val fontSize450: TextUnit = LemonadeFontSizes.FontSize450.sp,
    override val fontSize500: TextUnit = LemonadeFontSizes.FontSize500.sp,
    override val fontSize600: TextUnit = LemonadeFontSizes.FontSize600.sp,
    override val fontSize700: TextUnit = LemonadeFontSizes.FontSize700.sp,
    override val fontSize800: TextUnit = LemonadeFontSizes.FontSize800.sp,
    override val fontSize900: TextUnit = LemonadeFontSizes.FontSize900.sp,
    override val fontSize1000: TextUnit = LemonadeFontSizes.FontSize1000.sp,
    override val fontSize1200: TextUnit = LemonadeFontSizes.FontSize1200.sp,
    override val fontSize1400: TextUnit = LemonadeFontSizes.FontSize1400.sp,
    override val fontSize1600: TextUnit = LemonadeFontSizes.FontSize1600.sp,
    override val fontSize1800: TextUnit = LemonadeFontSizes.FontSize1800.sp,
): LemonadeFontSizeValues
