package com.teya.lemonade

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.teya.lemonade.core.LemonadeRadius

/**
 * Lemonade Design System Radius tokens.
 * Provides a consistent and scalable way to manage radius across interfaces.
 * These values can be used for cards, chips and rounded layouts in general.
 *
 *
 * Auto-generated content.
 *
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 *
 * This file is automatically generated by the scripts/kmp-radius-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 *
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-radius-token-converter.main.kts
 *
 * @generated by scripts/kmp-radius-token-converter.main.kts
 */
public val LemonadeRadius.dp: Dp
    get() {
        return when (this) {
            LemonadeRadius.Radius0 -> 0.dp
            LemonadeRadius.Radius50 -> 2.dp
            LemonadeRadius.Radius100 -> 4.dp
            LemonadeRadius.Radius150 -> 6.dp
            LemonadeRadius.Radius200 -> 8.dp
            LemonadeRadius.Radius300 -> 12.dp
            LemonadeRadius.Radius400 -> 16.dp
            LemonadeRadius.Radius500 -> 20.dp
            LemonadeRadius.Radius600 -> 24.dp
            LemonadeRadius.Radius800 -> 32.dp
            LemonadeRadius.RadiusFull -> 999.dp
        }
    }

public interface LemonadeRadiusValues {
    public val radius0: Dp
    public val radius50: Dp
    public val radius100: Dp
    public val radius150: Dp
    public val radius200: Dp
    public val radius300: Dp
    public val radius400: Dp
    public val radius500: Dp
    public val radius600: Dp
    public val radius800: Dp
    public val radiusFull: Dp
}

public interface LemonadeShapes {
    public val radius0: Shape
    public val radius50: Shape
    public val radius100: Shape
    public val radius150: Shape
    public val radius200: Shape
    public val radius300: Shape
    public val radius400: Shape
    public val radius500: Shape
    public val radius600: Shape
    public val radius800: Shape
    public val radiusFull: Shape
}

@Stable
internal data class InternalLemonadeRadiusValues(
    override val radius0: Dp = LemonadeRadius.Radius0.dp,
    override val radius50: Dp = LemonadeRadius.Radius50.dp,
    override val radius100: Dp = LemonadeRadius.Radius100.dp,
    override val radius150: Dp = LemonadeRadius.Radius150.dp,
    override val radius200: Dp = LemonadeRadius.Radius200.dp,
    override val radius300: Dp = LemonadeRadius.Radius300.dp,
    override val radius400: Dp = LemonadeRadius.Radius400.dp,
    override val radius500: Dp = LemonadeRadius.Radius500.dp,
    override val radius600: Dp = LemonadeRadius.Radius600.dp,
    override val radius800: Dp = LemonadeRadius.Radius800.dp,
    override val radiusFull: Dp = LemonadeRadius.RadiusFull.dp,
) : LemonadeRadiusValues

@Stable
internal data class InternalLemonadeShapes(
    override val radius0: Shape = RoundedCornerShape(size = LemonadeRadius.Radius0.dp),
    override val radius50: Shape = RoundedCornerShape(size = LemonadeRadius.Radius50.dp),
    override val radius100: Shape = RoundedCornerShape(size = LemonadeRadius.Radius100.dp),
    override val radius150: Shape = RoundedCornerShape(size = LemonadeRadius.Radius150.dp),
    override val radius200: Shape = RoundedCornerShape(size = LemonadeRadius.Radius200.dp),
    override val radius300: Shape = RoundedCornerShape(size = LemonadeRadius.Radius300.dp),
    override val radius400: Shape = RoundedCornerShape(size = LemonadeRadius.Radius400.dp),
    override val radius500: Shape = RoundedCornerShape(size = LemonadeRadius.Radius500.dp),
    override val radius600: Shape = RoundedCornerShape(size = LemonadeRadius.Radius600.dp),
    override val radius800: Shape = RoundedCornerShape(size = LemonadeRadius.Radius800.dp),
    override val radiusFull: Shape = RoundedCornerShape(size = LemonadeRadius.RadiusFull.dp),
) : LemonadeShapes
