package com.teya.lemonade

import com.teya.lemonade.core.LemonadeShadow

/**
 * Auto-generated content.
 * 
 * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
 * 
 * This file is automatically generated by the scripts/kmp-shadow-token-converter.main.kts script.
 * All changes will be overwritten when the script is run again.
 * 
 * To add updated content:
 * 1. Add your file to the tokens/ directory
 * 2. Run: kotlin scripts/kmp-shadow-token-converter.main.kts
 * 
 * @generated by scripts/kmp-shadow-token-converter.main.kts
 */
internal val LemonadeShadow.shadowDataSequence: Sequence<LemonadeShadowData>
    get() {
        return when (this) {
        LemonadeShadow.Large -> sequenceOf(
            LemonadeShadowData(
                blur = 1.0f,
                spread = 0.0f,
                offsetX = 0.0f,
                offsetY = 1.0f,
            ),
            LemonadeShadowData(
                blur = 8.0f,
                spread = -8.0f,
                offsetX = 0.0f,
                offsetY = 8.0f,
            ),
            LemonadeShadowData(
                blur = 28.0f,
                spread = -12.0f,
                offsetX = 0.0f,
                offsetY = 24.0f,
            ),
            LemonadeShadowData(
                blur = 48.0f,
                spread = -8.0f,
                offsetX = 0.0f,
                offsetY = 32.0f,
            ),
        )
        LemonadeShadow.Medium -> sequenceOf(
            LemonadeShadowData(
                blur = 1.0f,
                spread = 0.0f,
                offsetX = 0.0f,
                offsetY = 1.0f,
            ),
            LemonadeShadowData(
                blur = 32.0f,
                spread = -6.0f,
                offsetX = 0.0f,
                offsetY = 16.0f,
            ),
        )
        LemonadeShadow.Small -> sequenceOf(
            LemonadeShadowData(
                blur = 1.0f,
                spread = 0.0f,
                offsetX = 0.0f,
                offsetY = 1.0f,
            ),
            LemonadeShadowData(
                blur = 6.0f,
                spread = -3.0f,
                offsetX = 0.0f,
                offsetY = 4.0f,
            ),
        )
        LemonadeShadow.Xsmall -> sequenceOf(
            LemonadeShadowData(
                blur = 1.0f,
                spread = 0.0f,
                offsetX = 0.0f,
                offsetY = 1.0f,
            ),
            LemonadeShadowData(
                blur = 3.0f,
                spread = -3.0f,
                offsetX = 0.0f,
                offsetY = 3.0f,
            ),
        )
        LemonadeShadow.None -> sequenceOf(
            LemonadeShadowData(
                blur = 0f,
                spread = 0f,
                offsetX = 0f,
                offsetY = 0f,
            ),
        )
        }
    }

