import SwiftUI

// MARK: - Color Namespace Extensions

/// Enables shorthand color access like `.content.contentPrimary`
///
/// Colors automatically adapt to light/dark mode via Asset Catalog.
///
/// ## Usage
/// ```swift
/// Text("Hello")
///     .foregroundStyle(.content.contentPrimary)
///     .background(.bg.bgDefault)
/// ```
///
///  Auto-generated content.
///  ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️
///  @generated by scripts/swiftui-color-assets-generator.main.kts

// MARK: - Interaction Colors Namespace

public struct LemonadeInteractionColorsShorthand {
    public var bgNeutralSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-neutral-subtle-interactive", bundle: .lemonade) }
    public var bgPositiveSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-positive-subtle-interactive", bundle: .lemonade) }
    public var bgInfoSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-info-subtle-interactive", bundle: .lemonade) }
    public var bgNeutralInteractive: Color { Color("lemonade-interaction-interactive-background-bg-neutral-interactive", bundle: .lemonade) }
    public var bgBrandHighInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-high-interactive", bundle: .lemonade) }
    public var bgDefaultInteractive: Color { Color("lemonade-interaction-interactive-background-bg-default-interactive", bundle: .lemonade) }
    public var bgCautionInteractive: Color { Color("lemonade-interaction-interactive-background-bg-caution-interactive", bundle: .lemonade) }
    public var bgPositiveInteractive: Color { Color("lemonade-interaction-interactive-background-bg-positive-interactive", bundle: .lemonade) }
    public var bgSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-subtle-interactive", bundle: .lemonade) }
    public var bgInfoInteractive: Color { Color("lemonade-interaction-interactive-background-bg-info-interactive", bundle: .lemonade) }
    public var bgCautionSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-caution-subtle-interactive", bundle: .lemonade) }
    public var bgCriticalInteractive: Color { Color("lemonade-interaction-interactive-background-bg-critical-interactive", bundle: .lemonade) }
    public var bgBrandInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-interactive", bundle: .lemonade) }
    public var bgElevatedInteractive: Color { Color("lemonade-interaction-interactive-background-bg-elevated-interactive", bundle: .lemonade) }
    public var bgCriticalSubtleInteractive: Color { Color("lemonade-interaction-interactive-background-bg-critical-subtle-interactive", bundle: .lemonade) }
    public var bgDefaultPressed: Color { Color("lemonade-interaction-pressed-background-bg-default-pressed", bundle: .lemonade) }
    public var bgSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-subtle-pressed", bundle: .lemonade) }
    public var bgElevatedPressed: Color { Color("lemonade-interaction-pressed-background-bg-elevated-pressed", bundle: .lemonade) }
    public var bgBrandPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-pressed", bundle: .lemonade) }
    public var bgBrandHighPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-high-pressed", bundle: .lemonade) }
    public var bgCriticalPressed: Color { Color("lemonade-interaction-pressed-background-bg-critical-pressed", bundle: .lemonade) }
    public var bgCautionPressed: Color { Color("lemonade-interaction-pressed-background-bg-caution-pressed", bundle: .lemonade) }
    public var bgInfoPressed: Color { Color("lemonade-interaction-pressed-background-bg-info-pressed", bundle: .lemonade) }
    public var bgPositivePressed: Color { Color("lemonade-interaction-pressed-background-bg-positive-pressed", bundle: .lemonade) }
    public var bgNeutralPressed: Color { Color("lemonade-interaction-pressed-background-bg-neutral-pressed", bundle: .lemonade) }
    public var bgCriticalSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-critical-subtle-pressed", bundle: .lemonade) }
    public var bgCautionSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-caution-subtle-pressed", bundle: .lemonade) }
    public var bgInfoSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-info-subtle-pressed", bundle: .lemonade) }
    public var bgPositiveSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-positive-subtle-pressed", bundle: .lemonade) }
    public var bgNeutralSubtlePressed: Color { Color("lemonade-interaction-pressed-background-bg-neutral-subtle-pressed", bundle: .lemonade) }
    public var bgElevatedHighInteractive: Color { Color("lemonade-interaction-interactive-background-bg-elevated-high-interactive", bundle: .lemonade) }
    public var bgBrandElevatedInteractive: Color { Color("lemonade-interaction-interactive-background-bg-brand-elevated-interactive", bundle: .lemonade) }
    public var bgBrandElevatedPressed: Color { Color("lemonade-interaction-pressed-background-bg-brand-elevated-pressed", bundle: .lemonade) }
}

// MARK: - Border Colors Namespace

public struct LemonadeBorderColorsShorthand {
    public var borderBrandInverse: Color { Color("lemonade-border-inverse-border-brand-inverse", bundle: .lemonade) }
    public var borderSelectedInverse: Color { Color("lemonade-border-inverse-border-selected-inverse", bundle: .lemonade) }
    public var borderNeutralMediumInverse: Color { Color("lemonade-border-inverse-border-neutral-medium-inverse", bundle: .lemonade) }
    public var borderNeutralLowInverse: Color { Color("lemonade-border-inverse-border-neutral-low-inverse", bundle: .lemonade) }
    public var borderAlwaysDark: Color { Color("lemonade-border-fixed-border-always-dark", bundle: .lemonade) }
    public var borderPositiveSubtle: Color { Color("lemonade-border-voice-border-positive-subtle", bundle: .lemonade) }
    public var borderInfoSubtle: Color { Color("lemonade-border-voice-border-info-subtle", bundle: .lemonade) }
    public var borderCautionSubtle: Color { Color("lemonade-border-voice-border-caution-subtle", bundle: .lemonade) }
    public var borderCriticalSubtle: Color { Color("lemonade-border-voice-border-critical-subtle", bundle: .lemonade) }
    public var borderPositive: Color { Color("lemonade-border-voice-border-positive", bundle: .lemonade) }
    public var borderInfo: Color { Color("lemonade-border-voice-border-info", bundle: .lemonade) }
    public var borderCaution: Color { Color("lemonade-border-voice-border-caution", bundle: .lemonade) }
    public var borderOnBrandMedium: Color { Color("lemonade-border-brand-border-on-brand-medium", bundle: .lemonade) }
    public var borderBrand: Color { Color("lemonade-border-brand-border-brand", bundle: .lemonade) }
    public var borderSelected: Color { Color("lemonade-border-border-selected", bundle: .lemonade) }
    public var borderOnBrandLow: Color { Color("lemonade-border-brand-border-on-brand-low", bundle: .lemonade) }
    public var borderOnBrandHigh: Color { Color("lemonade-border-brand-border-on-brand-high", bundle: .lemonade) }
    public var borderCritical: Color { Color("lemonade-border-voice-border-critical", bundle: .lemonade) }
    public var borderNeutralLow: Color { Color("lemonade-border-border-neutral-low", bundle: .lemonade) }
    public var borderNeutralMedium: Color { Color("lemonade-border-border-neutral-medium", bundle: .lemonade) }
    public var borderAlwaysLight: Color { Color("lemonade-border-fixed-border-always-light", bundle: .lemonade) }
    public var borderNeutralHigh: Color { Color("lemonade-border-border-neutral-high", bundle: .lemonade) }
    public var borderNeutralHighInverse: Color { Color("lemonade-border-inverse-border-neutral-high-inverse", bundle: .lemonade) }
}

// MARK: - Content Colors Namespace

public struct LemonadeContentColorsShorthand {
    public var contentOnBrandLow: Color { Color("lemonade-content-brand-content-on-brand-low", bundle: .lemonade) }
    public var contentBrand: Color { Color("lemonade-content-brand-content-brand", bundle: .lemonade) }
    public var contentCaution: Color { Color("lemonade-content-voice-content-caution", bundle: .lemonade) }
    public var contentInfo: Color { Color("lemonade-content-voice-content-info", bundle: .lemonade) }
    public var contentTertiary: Color { Color("lemonade-content-content-tertiary", bundle: .lemonade) }
    public var contentAlwaysLight: Color { Color("lemonade-content-fixed-content-always-light", bundle: .lemonade) }
    public var contentSecondary: Color { Color("lemonade-content-content-secondary", bundle: .lemonade) }
    public var contentPrimaryInverse: Color { Color("lemonade-content-inverse-content-primary-inverse", bundle: .lemonade) }
    public var contentPositive: Color { Color("lemonade-content-voice-content-positive", bundle: .lemonade) }
    public var contentTertiaryInverse: Color { Color("lemonade-content-inverse-content-tertiary-inverse", bundle: .lemonade) }
    public var contentAlwaysDark: Color { Color("lemonade-content-fixed-content-always-dark", bundle: .lemonade) }
    public var contentNeutral: Color { Color("lemonade-content-voice-content-neutral", bundle: .lemonade) }
    public var contentBrandInverse: Color { Color("lemonade-content-inverse-content-brand-inverse", bundle: .lemonade) }
    public var contentSecondaryInverse: Color { Color("lemonade-content-inverse-content-secondary-inverse", bundle: .lemonade) }
    public var contentCritical: Color { Color("lemonade-content-voice-content-critical", bundle: .lemonade) }
    public var contentOnBrandHigh: Color { Color("lemonade-content-brand-content-on-brand-high", bundle: .lemonade) }
    public var contentPrimary: Color { Color("lemonade-content-content-primary", bundle: .lemonade) }
    public var contentCriticalOnColor: Color { Color("lemonade-content-voice-on color-content-critical-on-color", bundle: .lemonade) }
    public var contentCautionOnColor: Color { Color("lemonade-content-voice-on color-content-caution-on-color", bundle: .lemonade) }
    public var contentInfoOnColor: Color { Color("lemonade-content-voice-on color-content-info-on-color", bundle: .lemonade) }
    public var contentPositiveOnColor: Color { Color("lemonade-content-voice-on color-content-positive-on-color", bundle: .lemonade) }
    public var contentNeutralOnColor: Color { Color("lemonade-content-voice-on color-content-neutral-on-color", bundle: .lemonade) }
    public var contentBrandHigh: Color { Color("lemonade-content-brand-content-brand-high", bundle: .lemonade) }
}

// MARK: - Background Colors Namespace

public struct LemonadeBackgroundColorsShorthand {
    public var bgTransparent: Color { Color("lemonade-background-fixed-bg-transparent", bundle: .lemonade) }
    public var bgAlwaysLight: Color { Color("lemonade-background-fixed-bg-always-light", bundle: .lemonade) }
    public var bgAlwaysDark: Color { Color("lemonade-background-fixed-bg-always-dark", bundle: .lemonade) }
    public var bgDefaultInverse: Color { Color("lemonade-background-inverse-bg-default-inverse", bundle: .lemonade) }
    public var bgNeutralSubtle: Color { Color("lemonade-background-voice-bg-neutral-subtle", bundle: .lemonade) }
    public var bgCautionSubtle: Color { Color("lemonade-background-voice-bg-caution-subtle", bundle: .lemonade) }
    public var bgCriticalSubtle: Color { Color("lemonade-background-voice-bg-critical-subtle", bundle: .lemonade) }
    public var bgNeutral: Color { Color("lemonade-background-voice-bg-neutral", bundle: .lemonade) }
    public var bgBrandSubtle: Color { Color("lemonade-background-brand-bg-brand-subtle", bundle: .lemonade) }
    public var bgSubtleInverse: Color { Color("lemonade-background-inverse-bg-subtle-inverse", bundle: .lemonade) }
    public var bgBrandElevated: Color { Color("lemonade-background-brand-bg-brand-elevated", bundle: .lemonade) }
    public var bgPositiveSubtle: Color { Color("lemonade-background-voice-bg-positive-subtle", bundle: .lemonade) }
    public var bgDefault: Color { Color("lemonade-background-bg-default", bundle: .lemonade) }
    public var bgCritical: Color { Color("lemonade-background-voice-bg-critical", bundle: .lemonade) }
    public var bgBrandHigh: Color { Color("lemonade-background-brand-bg-brand-high", bundle: .lemonade) }
    public var bgCaution: Color { Color("lemonade-background-voice-bg-caution", bundle: .lemonade) }
    public var bgBrand: Color { Color("lemonade-background-brand-bg-brand", bundle: .lemonade) }
    public var bgElevated: Color { Color("lemonade-background-bg-elevated", bundle: .lemonade) }
    public var bgElevatedInverse: Color { Color("lemonade-background-inverse-bg-elevated-inverse", bundle: .lemonade) }
    public var bgSubtle: Color { Color("lemonade-background-bg-subtle", bundle: .lemonade) }
    public var bgInfo: Color { Color("lemonade-background-voice-bg-info", bundle: .lemonade) }
    public var bgPositive: Color { Color("lemonade-background-voice-bg-positive", bundle: .lemonade) }
    public var bgInfoSubtle: Color { Color("lemonade-background-voice-bg-info-subtle", bundle: .lemonade) }
    public var bgElevatedHigh: Color { Color("lemonade-background-bg-elevated-high", bundle: .lemonade) }
}

// MARK: - ShapeStyle Extensions

public extension ShapeStyle where Self == Color {
    /// Interaction color tokens
    /// Usage: `.foregroundStyle(.interaction.borderNeutralMedium)`
    static var interaction: LemonadeInteractionColorsShorthand { LemonadeInteractionColorsShorthand() }

    /// Border color tokens
    /// Usage: `.foregroundStyle(.border.borderNeutralMedium)`
    static var border: LemonadeBorderColorsShorthand { LemonadeBorderColorsShorthand() }

    /// Content color tokens
    /// Usage: `.foregroundStyle(.content.contentPrimary)`
    static var content: LemonadeContentColorsShorthand { LemonadeContentColorsShorthand() }

    /// Background color tokens
    /// Usage: `.foregroundStyle(.bg.bgDefault)`
    static var bg: LemonadeBackgroundColorsShorthand { LemonadeBackgroundColorsShorthand() }

}
