#!/usr/bin/env kotlin

import java.io.File

private fun convertSvgToVectorDrawable(svgContent: String): String {
    val widthRegex = Regex("width=\"([^\"]*)")
    val heightRegex = Regex("height=\"([^\"]*)")
    val viewBoxRegex = Regex("viewBox=\"([^\"]*)")
    
    val width = widthRegex.find(svgContent)?.groupValues?.get(1)?.replace("px", "")?.toDoubleOrNull()?.toInt() ?: 24
    val height = heightRegex.find(svgContent)?.groupValues?.get(1)?.replace("px", "")?.toDoubleOrNull()?.toInt() ?: 24
    val viewBox = viewBoxRegex.find(svgContent)?.groupValues?.get(1)?.split(" ")
    
    val viewportWidth = viewBox?.getOrNull(2)?.toDoubleOrNull() ?: width.toDouble()
    val viewportHeight = viewBox?.getOrNull(3)?.toDoubleOrNull() ?: height.toDouble()
    
    val vectorDrawable = buildString {
        appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        appendLine("<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"")
        appendLine("    android:width=\"${width}dp\"")
        appendLine("    android:height=\"${height}dp\"")
        appendLine("    android:viewportWidth=\"$viewportWidth\"")
        appendLine("    android:viewportHeight=\"$viewportHeight\">")
        
        val pathRegex = Regex("<path[^>]*d=\"([^\"]*)[^>]*>")
        val fillRegex = Regex("fill=\"([^\"]*)")
        val fillRuleRegex = Regex("fill-rule=\"([^\"]*)")
        
        pathRegex.findAll(svgContent).forEach { match ->
            val pathData = match.groupValues[1]
            val fillMatch = fillRegex.find(match.value)
            val fillRuleMatch = fillRuleRegex.find(match.value)
            
            appendLine("    <path")
            appendLine("        android:pathData=\"$pathData\"")
            
            val fillColor = fillMatch?.groupValues?.get(1) ?: "black"
            if (fillColor != "none") {
                val androidColor = when(fillColor) {
                    "black" -> "#FF000000"
                    "white" -> "#FFFFFFFF"
                    else -> fillColor
                }
                appendLine("        android:fillColor=\"$androidColor\"")
            }
            
            fillRuleMatch?.let {
                val fillRule = when (it.groupValues[1]) {
                    "evenodd" -> "evenOdd"
                    else -> "nonZero"
                }
                appendLine("        android:fillType=\"$fillRule\"")
            }
            
            appendLine("        />")
        }
        
        appendLine("</vector>")
    }
    
    return vectorDrawable
}

private fun generateIconsCore(
    iconPackName: String,
    iconNames: List<String>,
) {
    val coreIconsFile = File("kmp/core/src/commonMain/kotlin/com/teya/lemonade/core/$iconPackName.kt")
    
    val coreContent = buildString {
        appendLine("package com.teya.lemonade.core")
        appendLine()
        appendLine("/**")
        appendLine(" * Auto-generated enum class containing all icons converted from SVG files.")
        appendLine(" * ")
        appendLine(" * ⚠️ **DO NOT MODIFY THIS FILE MANUALLY** ⚠️")
        appendLine(" * ")
        appendLine(" * This file is automatically generated by the svg-converter.main.kts script.")
        appendLine(" * All changes will be overwritten when the script is run again.")
        appendLine(" * ")
        appendLine(" * To add new icons:")
        appendLine(" * 1. Add your SVG file to the svg/pack-dir/ directory")
        appendLine(" * 2. Run: kotlin svg-converter.main.kts")
        appendLine(" * ")
        appendLine(" * @generated by svg-converter.main.kts")
        appendLine(" */")
        appendLine("public enum class $iconPackName: LemonadeAsset {")
        
        iconNames.forEachIndexed { index, iconName ->
            val enumName = iconName.split("-").joinToString("") { it.replaceFirstChar { char -> char.uppercase() } }
            val suffix = if (index == iconNames.size - 1) "" else ","
            appendLine("    $enumName$suffix")
        }
        
        appendLine("}")
    }
    
    coreIconsFile.writeText(coreContent)
    println("✓ Generated core $iconPackName.kt with ${iconNames.size} icons")
}

private fun generateIconsExtension(
    iconPackName: String,
    iconNames: List<String>,
) {
    val uiExtensionFile = File("kmp/ui/src/commonMain/kotlin/com/teya/lemonade/${iconPackName}Extension.kt")
    
    val extensionContent = buildString {
        appendLine("package com.teya.lemonade")
        appendLine()
        appendLine("import com.teya.lemonade.core.${iconPackName}")
        appendLine("import org.jetbrains.compose.resources.DrawableResource")
        appendLine()
        appendLine("/**")
        appendLine(" * Auto-generated extension for $iconPackName enum providing drawable resources.")
        appendLine(" */")
        appendLine("public val ${iconPackName}.drawableResource: DrawableResource")
        appendLine("    get() = when (this) {")
        
        iconNames.forEach { iconName ->
            val enumName = iconName.split("-").joinToString("") { it.replaceFirstChar { char -> char.uppercase() } }
            val resourceName = "gen_" + iconName.replace("-", "_")
            appendLine("        ${iconPackName}.$enumName -> LemonadeRes.drawable.$resourceName")
        }
        
        appendLine("    }")
    }
    
    uiExtensionFile.writeText(extensionContent)
    println("✓ Generated ${iconPackName}Extension.kt with ${iconNames.size} icons")
}

private fun getArgs(): Pair<String, String> {
    if (args.isEmpty()) {
        error("No arguments provided! [-pack-name, -pack-dir]")
    }

    val packNameArg = args.indexOf("-pack-name")
    val packName = args.getOrNull(packNameArg + 1)
        ?: error("'-pack-name' argument not found")

    println("Pack Name: $packName")

    val packDirArg = args.indexOf("-pack-dir")
    val packDir = args.getOrNull(packDirArg + 1)
        ?: error("'-pack-dir' argument not found")

    println("Pack Directory: $packDir")

    return packName to packDir
}

fun main() {
    val (packageName, packageDir) = getArgs()

    val svgDir = File("svg/$packageDir")
    val outputDir = File("kmp/ui/src/commonMain/composeResources/drawable")
    
    if (!svgDir.exists()) {
        println("SVG directory '$svgDir' not found!")
        return
    }
    
    if (!outputDir.exists()) {
        outputDir.mkdirs()
    }
    
    println("Converting SVG files to vector drawables...")
    
    val iconNames = mutableListOf<String>()
    
    svgDir.listFiles { file -> file.extension == "svg" }?.forEach { svgFile ->
        try {
            val svgContent = svgFile.readText()
            val fileName = svgFile.nameWithoutExtension
            val vectorDrawable = convertSvgToVectorDrawable(svgContent)
            
            val outputFileName = fileName.replace("-", "_")
            val outputFile = File(outputDir, "gen_$outputFileName.xml")
            outputFile.writeText(vectorDrawable)
            
            iconNames.add(fileName)
            println("✓ Converted ${svgFile.name} -> ${outputFile.name}")
        } catch (e: Exception) {
            println("✗ Failed to convert ${svgFile.name}: ${e.message}")
        }
    }
    
    println("Conversion complete!")

    if (iconNames.isNotEmpty()) {
        val sortedIconNames = iconNames.sorted()
        generateIconsCore(
            iconPackName = packageName,
            iconNames = sortedIconNames,
        )
        generateIconsExtension(
            iconPackName = packageName,
            iconNames = sortedIconNames,
        )
    } else {
        println("No icons found.")
    }
}

main()