name: Lemonade
options:
  bundleIdPrefix: com.teya.lemonade
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"

targets:
  Lemonade:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Lemonade
        type: group
        excludes:
          - "**/Resources/**"
      - path: Sources/Lemonade/Resources/Assets.xcassets
        type: file
        buildPhase: resources
      - path: Sources/Lemonade/Resources/Fonts
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.teya.lemonade
        INFOPLIST_FILE: Sources/Lemonade/Info.plist
        DEFINES_MODULE: YES
        PRODUCT_NAME: Lemonade
        SKIP_INSTALL: NO
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        SWIFT_EMIT_LOC_STRINGS: YES

  LemonadeSampleApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "16.0"
    sources:
      - path: SampleApp
        type: group
    dependencies:
      - target: Lemonade
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.teya.lemonade.sampleapp
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_NAME: LemonadeSampleApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
